### ISSUE TITLE
Suggestion: minimize waste of vertical space with subsection titles

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#10]
Using the image presented in the release changelog, I would like to ask to improve the use of vertical space (even if optional and off by default, so some people like me can use the more compact mode) by moving titles of subsections on the first line of their content rather than on the top of their content. This will save a lot of vertical space for games with lots of items/abilities/attacks (PF2 on mid/late tier for example)

Also there's no need to duplicate the section title as a header as this is a known information. In this case, I would remove the second "Actions" using subsection font. 

![image](https://user-images.githubusercontent.com/4083812/214812903-cb641b0c-bddc-4579-b734-ee75f61ad229.png)

**Comment by Larkinabout** [comment]
I'll have a look at optional positioning, but the current layout affords some benefits over the old way that I wouldn't want to lose, namely: 

- Titles can be as long as they want without messing with the layout. I've found some of the Pathfinder 2 spell categories can be especially long.
- Other info text and icons can be added alongside the subtitle.
- It allows for easy visible nesting of subcategories.
- The duplication of the heading only occurs where they are the same word. For example, users may want to add 'Actions' and 'Bonus Actions' to a category called 'Combat' at which point the subtitles are useful info.

On the latter, I can see about an option to hide each one by preference.

**Comment by Larkinabout** [comment]
Didn't mean to close the issue!

**Comment by apoapostolov** [comment]
Thanks for the reply. I see the benefit of having subsection titles and yes, you can use the full width to add more content there. This is why I suggested this to be an option, off by default. Normally, people will use that option ONLY when they hit the heigth limit in very high-tier games. 

The only thing I suggest not to do by default, is doubling the title of the section with its own small header below, i.e. Actions and Actions right below it. Unless you have a good reason for this

**Comment by Larkinabout** [comment]
Easiest solution is to allow users to hide subtitles they don't want to see. Trying to do it programmatically would be a bit of a nightmare. I'll have a look once Token Action HUD PF2 is out of the way.

**Comment by Larkinabout** [comment]
![token-action-hud-hide-title](https://user-images.githubusercontent.com/105953297/215357550-34bbdf47-d759-43dc-b629-fa4e3ed63940.gif)

**Comment by apoapostolov** [comment]
Thank you! This is a good way to move subsection titles as well via an
option.

**Comment by Larkinabout** [comment]
Closing as group titles to the left is unlikely to happen and users can now hide titles and add a group image where they want to save vertical space.
