### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Stountain** [Larkinabout/fvtt-token-action-hud-core#101]
**Describe your idea**
A description of your idea.
Thank you for Token Action Hud Core it has been very useful to our Pathfinder 2e group.
One of my players has vision issues and was asking if there was a way to make the backgrounds of the HUD columns opaque.

**Versions**
- Token Action HUD System: token-action-hud-core + Token Action HUD Pathfinder 2e
- System: Pathfinder 2e
![Screenshot 2023-04-12 145649](https://user-images.githubusercontent.com/85375714/231595176-594b8ee9-b68d-4e77-8325-cec612899e42.jpg)

**Comment by Larkinabout** [comment]
Hi @Stountain, if you install the [Color Picker](https://foundryvtt.com/packages/color-picker) module, the Token Action HUD Core module settings has some additional options to color the background and buttons.

**Comment by Stountain** [comment]
Thank you very much
