### ISSUE TITLE
[FEATURE] render hook

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#103]
It would be awesome if TAH could fire off an "action hud rendered" hook. This would allow a lot more customization on the hud if I wanted to do something a lot more complex that can't be done with just css.

I'm imagining something like `Hooks.callAll('tah-core-hud-rendered', node);`

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.0.
