### ISSUE TITLE
[BUG] flags bloat user.db file size and cause issues with The Forge

### ISSUE THREAD

**Issue by finalfrog** [Larkinabout/fvtt-token-action-hud-core#106]
**Describe the bug**
I ran into an issue today where The Forge got confused by my user.db being excessively large causing it to treat it as corrupted.

**Steps to reproduce**
1. Activate module with 6-7 players in campaign

Expected:
user.db is only a couple of KB

Observed:
user.db is 3.3 MB: [users.zip](https://github.com/Larkinabout/fvtt-token-action-hud-core/files/11245257/users.zip)

**Versions:**
- Token Action HUD Core: 1.3.2
- Token Action HUD System: token-action-hud-pf2e 1.3.1
- System: pf2e 4.10.4
- Foundry VTT: 10.291
- Browser: Firefox 113.0b3

**Notes:**
I had to basically reset The Forge user configuration for the campaign today because it thought my user.db was corrupt. I showed my user.db to KaKaRoTo and he said that user.db shouldn't be larger than a couple KB and was confused why a module would put MBs worth of data into it. I'm going to have to disable this module to avoid having this issue again, so I figured I should post a bug report.

I realize whether this is a bug on Forge or on this module is probably a matter of perspective. If you want to debate it and see if The Forge can make changes to accommodate flags in the user.db talk to KaKaRoTo.

**Comment by Larkinabout** [comment]
There's probably quite a bit that could be done to minimise flag data stored against the users, however it would be useful to know what is the current upper limit for The Forge. With the availability of flags in the user object, any module could increase the size of the users.db file, it just so happens that Token Action HUD Core uses it readily.

There's already some changes in the next release to move some data to the actor flag and to not store actions data against the user. That will clear out quite a bit of data. I'll also look to stop storing the defaults against the user and just load them in from the module files.

**Comment by Larkinabout** [comment]
Spoke with The Forge team. The next release of Token Action HUD Core will reduce the data head within the user flags and The Forge team will also look at increasing allowable size of the users.db.

**Comment by Larkinabout** [comment]
Somewhat to be expected with the HUD saving to actor flags. Truncation of the database to remove logs seems to happen when you close and reopen a world. The next release reduces the number of times the actor flag data is updated to reduce db growth during play. The data that is stored, especially with the next release, is as small as it can be for actors, due to the HUD needing to know the layout and what actions are selected.

**Comment by Larkinabout** [comment]
Sorry, hust noted that this is increasing the scenes. I guess that means Foundry loads all of the actor data into the scene multiple times for every token, which would make the scene quite large with the HUD flag data. Not sure what I can do about that apart from keep trying to find ways to reduce the size. It's probably mean reducing the size of strings where possible as I'm not sure there's any more that can be stripped out.

Has this caused any issues or is it just something you've noticed with the file sizes?

**Comment by Larkinabout** [comment]
Self note to try always reloading actions on HUD update and not save the action state to flags except for id and whether it's selected by the user.

**Comment by MrPrimate** [comment]
I've not noticed any personal impact, but suspect it will start to impact world load time. I noticed it in some user submitted scene configs for DDB
