### ISSUE TITLE
PF2 Support

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#11]
This is more of a discussion than an issue. @Larkinabout what do you need to get a full PF2 support?

**Comment by Larkinabout** [comment]
It's next on the list assuming Token Action HUD Core is stable. It's just a matter of finding the time now.

**Comment by Larkinabout** [comment]
First release of [Token Action HUD Pathfinder 2](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e) is out and just waiting for approval from Foundry VTT. Any further issues/feature requests specifically for the Pathfinder 2 module can be raised over there.
