### ISSUE TITLE
[BUG] Can't set icons for categories after updating to 1.4

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#112]
**Describe the bug**
When I set an icon for a category, it does not save. Using 1.4 for core and dnd 5e.

**Comment by nschoenwald** [comment]
further testing shows that no editing seems to be working on the categories.

**Comment by Larkinabout** [comment]
Hmm, it seems to be working for me:
![image](https://user-images.githubusercontent.com/105953297/236046336-150e59d2-1241-4acb-8769-ae1a6f57227b.png)

Does it add the image at all?

**Comment by nschoenwald** [comment]
It does not save any changes, not to the icons and not to the categories themselves.

**Comment by nschoenwald** [comment]
I don't get any errors in console, but changes do not take effect.
<img width="618" alt="image" src="https://user-images.githubusercontent.com/72390280/236055287-4a613f16-5e94-4ddf-a6be-9efd31b527b0.png">

**Comment by Larkinabout** [comment]
Looks like it's saving something. Can you send me those files. They are located in the Foundry VTT data folder under 'token-action-hud-core'.

**Comment by nschoenwald** [comment]
I think this bug occured because installing the dnd5e system update to 1.4 didn't work at first and I launched the world before it was updated. After cleaning everything up and updating to 1.4 again, everything seems to work now.

**Comment by Larkinabout** [comment]
Good to hear!
