### ISSUE TITLE
[BUG] Group doesn't remain open when moving off title

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#115]
**Describe the bug**
With "Click to Open Categories" is NOT ticked, when I move the mouse over a title in the HUD then the entries in that menu appear, but as soon as I move the mouse down towards one of those displayed entries the menu disappears.

**Steps to reproduce**

**Versions:**
- Token Action HUD Core: 1.4.0
- Token Action HUD System: cyphersystem-dev
- System: cyphersystem 2.5.0
- Foundry VTT: 10.291
- Browser: foundry app on Windows 11

**Additional context**
Any additional context.

**Comment by farling42** [comment]
Only after toggling the "Grid" option off and on again did it start working.

**Comment by Larkinabout** [comment]
Yeah, I overhauled the CSS but failed to re-add the padding to stop the group closing when the cursor moves off the button. I'll have a release to fix it soon.
