### ISSUE TITLE
[BUG] Nested tabs with actions and groups have odd layout

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#116]
I have a group with 2 actions plus extra groups with their own actions. This is how it looks as a list
![image](https://user-images.githubusercontent.com/3664822/236252261-c417e017-0f8a-4a43-9c6f-5056d6a31dd1.png)

When I change it to a tabbed style it looks like this
![image](https://user-images.githubusercontent.com/3664822/236252455-120828d9-91b6-4965-9022-bff7b1d98c87.png)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.7.
