### ISSUE TITLE
[FEATURE] Use foundry's tooltip manager instead of title html data prop

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#118]
Using foundry's built in tooltip manager will give a more cohesive feel with the rest of the UI. Including allowing anything that customizes foundry's tooltips to work with the tooltips generated here.

**Comment by Larkinabout** [comment]
I'm planning to look at tooltips as part of #23 and will explore Foundry's built in tooltip manager.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.8.
