### ISSUE TITLE
[BUG] Need help: Undo "Reset HUD"?

### ISSUE THREAD

**Issue by ortegamarcel** [Larkinabout/fvtt-token-action-hud-core#119]
**Describe the problem**
I am implementing my own system integration. While testing, I used the "reset HUD" setting from this module. Since then no actions show up in the HUD anymore. It is loading, it also shows the Token/Character Name, but no Buttons to click. How can I bring back my actions? Even for other worlds, it doesn't work anymore.

**Steps to reproduce** (how I did it)
1. Go to the modules settings
2. Check 'Reset HUD'
3. Click 'Save'

**Versions:**
- Token Action HUD Core: 1.4.2
- Foundry VTT: 10.291

**Comment by Larkinabout** [comment]
If I understand, this is your own TAH system module?

If so, when you reset the HUD it pulls the data from the default layout provided by your system module. If you are providing a default layout, then it might be in the wrong format.

**Comment by ortegamarcel** [comment]
@Larkinabout yes, you understand it right. 

But thanks for the hint, it helped me. I think my problem was that I didn't use the `tokenActionHudCoreApiReady`-hook to load everything (inkl. defaults) or it was really a wrong format. Not sure, I'm pretty new to this TAH module.

**Comment by Larkinabout** [comment]
Glad you're making progress. Let me know if there's anything else you need help with.
