### ISSUE TITLE
[BUG] could not get initial migrate of flags to work unless file browse and upload permissions granted

### ISSUE THREAD

**Issue by modzy2** [Larkinabout/fvtt-token-action-hud-core#120]
**Describe the bug**
I could not get fresh logons of users to get the "successfully migrated flags" to happen (and creation of their json in the users folder) unless I provided file browse and upload permissions to "players" first. Without that their hud would not show up.  This happened even though I had a GM logged in always.  Is the file browse/upload permission an ongoing requirement to allow users to continue to manage their settings, or can I drop that permission again once the users folder is populated for each player?

**Versions:**
- Token Action HUD Core: [1.4.2]
- Token Action HUD System:  token-action-hud-dnd5e 1.4.1
- System:  dnd5e 2.1.5
- Foundry VTT: 10.291
- Browser:  Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by Larkinabout** [comment]
It shouldn't as the functions to to save data are executed through socketlib using the `executesGM` method. I'll run some tests to see if there's an issue.

**Comment by farling42** [comment]
It sounds like maybe the initial directory creation isn't being done by the GM?

A report of discord says that user needs file creation permissions to get it working in the first place, but they can be disabled afterwards.

**Comment by Larkinabout** [comment]
Yes, it's the initial migration from 1.3 to 1.4 that is failing. You're correct that that part isn't being passed through the socket to execute as the GM.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.3.
