### ISSUE TITLE
[BUG] Token Action HUD TheWitcherTRPG

### ISSUE THREAD

**Issue by Melkkart** [Larkinabout/fvtt-token-action-hud-core#121]
Hi, I will try to install, but, i recive error, I installa all modules recomended, but i have error, copy tex to Console:

foundry.js:59187 Errors were encountered while installing the package. Consult your console log (F12) for details.
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
error @ setup.js:284
progress @ setup.js:326
(anonymous) @ setup.js:594
_onProgress @ setup.js:594
x.emit @ index.mjs:136
value @ socket.js:278
value @ socket.js:265
value @ socket.js:235
x.emit @ index.mjs:136
value @ manager.js:200
x.emit @ index.mjs:136
value @ index.js:119
value @ manager.js:192
x.emit @ index.mjs:136
value @ socket.js:323
x.emit @ index.mjs:136
value @ transport.js:104
value @ transport.js:97
ws.onmessage @ websocket.js:79
setup.js:141 [fvtt-token-action-hud-TheWitcherTRPG] Metadata validation failed for module "fvtt-token-action-hud-TheWitcherTRPG": The file "scripts/polyfills.js" included by module fvtt-token-action-hud-TheWitcherTRPG does not exist

**Comment by Larkinabout** [comment]
Please raise this issue with the developer of the Token Action HUD The Witcher TRPG module.

**Comment by Melkkart** [comment]
I'm sorry, I don't know how I ended up here, my apologies.
