### ISSUE TITLE
[FEATURE] Show Token Action HUD TheWitcherTRPG in your Modules Description and README

### ISSUE THREAD

**Issue by ortegamarcel** [Larkinabout/fvtt-token-action-hud-core#123]
I created and released the Token Action HUD TheWitcherTRPG module. It would be nice, if you could list it here as well. I can also create a PR by myself if that is preferred?

Here are the Links:
* Foundry: https://foundryvtt.com/packages/fvtt-token-action-hud-thewitchertrpg
* Github: https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.4.
