### ISSUE TITLE
[BUG] Show unequipped items setting does nothing

### ISSUE THREAD

**Issue by MotoMoto1234** [Larkinabout/fvtt-token-action-hud-core#126]
**Describe the bug**
No matter what you do with the setting "show Unequipped Items" setting all unequipped items still show and it seems this can cause some categories/filters to display duplicate items

**Steps to reproduce**

**Versions:**
- Token Action HUD Core: [e.g. 0 1.0]
- Token Action HUD System: [e.g. token-action-hud-dnd5e 0.1.0]
- System: [e.g. dnd5e 2.0.3]
- Foundry VTT: [e.g. 10.291]
- Browser: [e.g. Google Chrome 108.0.5359.124]

**Additional context**
![image](https://user-images.githubusercontent.com/116308065/237039999-89a8f034-8bb4-43d2-8531-e349f848cb7c.png)  

![image](https://user-images.githubusercontent.com/116308065/237040088-617b64cd-bfe7-4f41-a5a3-d35d1f4d1190.png)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.4.
