### ISSUE TITLE
[BUG] Issue updating TAH system module for 1.4 compatibility

### ISSUE THREAD

**Issue by phildominguez** [Larkinabout/fvtt-token-action-hud-core#127]
**Describe the bug**
Hello, I'm the developer of the [Essence20 implementation](https://github.com/phildominguez/token-action-hud-essence20) of TAH. I've been having trouble getting my module to work correctly with with TAH Core 1.4 update.

When an actor is selected, no buttons show up for the HUD. The debug logs show groups being populated, but the actions are all empty:
![Screenshot 2023-05-11 203837](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/41161497/6540ca1f-4f79-48e2-afe8-96c59ee21426)

The groups are also not how I organized them in `DEFAULTS.layouts`. Compare to Core 1.3.2:
![Screenshot 2023-05-11 204410](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/41161497/76ba8b70-0fff-4c5d-a316-51af632b9f04)

When it didn't work out of the box, I followed the developer's update guide to try to get it working. In summary, I:
- Changed `categories` -> `layout` and `subcategories` -> `groups` in `DEFAULTS`
- Changed `addActionsToActionList()` to `addActions()`
- Removed references to `CategoryManager`
- Changed `ready` hook to `tokenActionHudCoreApiReady`

Things I did not change:
- `hasDerivedSubcategories` not used
- `addSubcategoryToActionList()` not used
- `sortItems()` not used
- `sortItemsByName()` not used
- `advancedCategoryOptions` not used

I've put up a [PR](https://github.com/phildominguez/token-action-hud-essence20/pull/1/files) if you'd like to see the changes.

**Versions:**
- Token Action HUD Core: 1.4.4
- Token Action HUD System: token-action-hud-essence20 0.1.0
- System: [Essence20 ](https://github.com/WookieeMatt/Essence20) 3.1.6
- Foundry VTT: 10.291
- Browser: Foundry client

Let me know what other info I can provide. Any suggestions would be greatly appreciated!

**Comment by Larkinabout** [comment]
https://github.com/phildominguez/token-action-hud-essence20/pull/2

**Comment by phildominguez** [comment]
@Larkinabout Holy cow, thanks so much! Working great now. Closing this out.
