### ISSUE TITLE
[FEATURE] Use "Persistent Storage" feature of Foundry V11

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#134]
Instead of storing your new json data files as a root folder in a user's userdata area, move this data to the "**persistent storage**" area that is available for modules to use.

Also, provide a migration for V10 users to have their files relocated automatically to the new location.

**Comment by Larkinabout** [comment]
Nice feature! Any chance this also allows users without file permissions to save to that location?

**Comment by Larkinabout** [comment]
https://github.com/foundryvtt/foundryvtt/issues/9708 - On hold until this issue is resolved.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.12.
