### ISSUE TITLE
[FEATURE] Large panels should scroll to their bottom when rendered if TAH is set to show them above instead of below

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#146]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/4083812/aa9ba1e0-101e-4450-a54d-008fb95b2e1b)

When Token Action HUD is set to be used on the bottom and render sections on the top, sections still are rendered normally scrolled to their top, causing the important items at the bottom (since the logic is showing the bottom things first closest to the mouse) to be scrolled out of the screen if there are too many items, and the user must scroll to the bottom manually each time to access them. This makes it very hard to guarantee that the closest to mouse options are not out of screen due to scrolling. 

By making section panels scroll to their bottom when using the "show on top" mode, the problem would be resolved, and if scrolling is needed to he top, the user will make it manually.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.12.

**Comment by apoapostolov** [comment]
Thank you!!
