### ISSUE TITLE
[FEATURE] Savage Worlds support

### ISSUE THREAD

**Issue by mrcomac** [Larkinabout/fvtt-token-action-hud-core#149]
**Savage Worlds**
I'm working on the Savage Worlds module
https://github.com/mrcomac/token-action-hud-swade

**Comment by Larkinabout** [comment]
@mclemente was also working on a version for SWADE. It may be worthwhile combining your efforts.

**Comment by mclemente** [comment]
I have barely anything to contribute, unfortunately. I am really behind on that, I didn't even got all the buttons to show up as they did on Classic, and didn't even looked at the roll handling yet.

Most I can contribute is the aesthetic things, like icons to skills and the `info1` data to attributes, skills, weapons (Classic's "green dice numbers").

**Comment by mrcomac** [comment]
@mclemente I have the basics working. I've sent to some DMs to test and send me feedbacks. After that I'll make a release for basic stuffs (attributes, skills, gears, powers, weapons, etc). For now my focus is have the code running and useful.

After those tests I will create a project release to set some goals and tasks. I can add you to contribute with icons and other non code stuffs. how it sounds to you?

**Comment by mclemente** [comment]
That would be great, thanks. Actually, I just sent a PR to add those to the project lol

**Comment by mrcomac** [comment]
that sounds awesome. I've merged it.

**Comment by Larkinabout** [comment]
I've added links to the Token Action HUD Core readme and Foundry VTT package page.

Now that the module is released, I'll go ahead and close this issue as resolved.
