### ISSUE TITLE
[BUG] Can't open HUD after updating from previous Token Action Hud module

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#15]
**Describe the bug**
I previously used the Token Action Hud module and wanted to change over to this one and the 5e module in order to use the new features like always showing the HUD, even if no token is selected. Unfortunately, the hud does not open at all and there are errors in the console:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/72390280/214857644-1e78ec4d-6f80-46a0-8042-2224428f7fe6.png">

**Versions:**
- Token Action HUD Core: 1.01
- Token Action HUD System: token-action-hud-dnd5e 1.01
- System: dnd5e 2.0.3
- Foundry VTT: 10.291
- Browser: Google Chrome 109.0.5414.119

**Comment by nschoenwald** [comment]
Apparently, using the options menu to reset the hud fixes this up to a point. The problem is, that this apparently has to be done every time you change the browser or delete cookies - when I log in as a player in private chrome window, I always have to reset the hud before it works.
Also, the spells section is named incorrectly: 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/72390280/214861697-51305793-ed81-4327-aeb5-335b5c24e99e.png">

**Comment by Larkinabout** [comment]
The HUD setup should persist across sessions as it saves its data to the user flags. Would you be able to enable the 'Enable Debugging' module setting, refresh Foundry, open the console (F12), filter for 'Token Action HUD' and send me over the results so I can take a look please?

**Comment by nschoenwald** [comment]
I think this was related to the module not being compatible with dnd5e 2.0.3. After upgrading to 2.1, the error was gone.

**Comment by Larkinabout** [comment]
I'll leave the minimum required version at 2.1.0 and move on as there's still the original Token Action HUD for anyone still to upgrade to the latest version of the system.
