### ISSUE TITLE
[BUG][PF2E] Alchemist Infused Weapons (bombs) stay on the Hud after resting and stacks.

### ISSUE THREAD

**Issue by Lnik3500** [Larkinabout/fvtt-token-action-hud-core#151]
**Describe the bug**
Playing as an alchemist, the player can craft temporary consummables, including bombs. Bombs are considered weapons and can be used as such in the hud, but after resting, they all automatically get deleted. After that the weapon still stays in the hud and can stack until foundry is refreshed.

**Steps to reproduce**
1. Using the pathfinder 2e system, select the alchemist class with its feats included (Infused reagents are the most important)
2. Add Alchemist's Fire on your daily crafting list and complete it (this should add selected bomb as a temporary weapon with the infused trait) 
3. You can see Alchemist's Fire or whatever selected bomb as a weapon in the token action, adding it as a category in the strikes
4. Click on the rest button, reseting your infused reagents and deleting your temporary weapon, you should see that the category for that weapon wasn't deleted.
6. Make your daily preparations again and it will add the category back but on a new one, still keeping the old one. You can stack this process infinitely.

**Versions:**
- Token Action HUD Core: 1.4.9
- Token Action HUD System: Pathfinder 2e 1.4.8
- System: Pathfinder 2e 5.0.1
- Foundry VTT: 11.302
- Browser: Any

**Additional context**
I don't know if I should've posted in PF2e version only, but it seemed to be an error related to Core.

**Comment by Larkinabout** [comment]
Am I doing something differently? The character sheet behaviour seems to keep the alchemist's fire following a rest and also add a new item group when it is crafted again after the rest. The HUD seems to just be replicating what is on the sheet and they disappear from the HUD when the item is deleted from the sheet.

![token-action-hud-pf2e-alchemists-fire](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/105953297/6c2f394e-baf0-4c7d-95be-71f80ccb364e)

**Comment by Larkinabout** [comment]
Closing this one as unable to reproduce and it's been open without a response for a while. If it's still an issue, let me know.
