### ISSUE TITLE
Token Action HUD fails on start up for one player [BUG]

### ISSUE THREAD

**Issue by jared112git** [Larkinabout/fvtt-token-action-hud-core#152]
**Describe the bug**
Token Action HUD Fails to work for one player on all browsers. Console Error: 

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/134901291/45f9b034-1ac5-4d53-8a07-0875c509e0ff)

Regardless of what the player or me as GM do nothing works to bring up the HUD. But all my other players don't have this issue.

**Steps to reproduce**
Before the player has even touched anything the error shows in the console.

**Versions:**
- Token Action HUD Core: 1.4.9
- Token Action HUD System: D&D 5e 1.4.5
- System: DnD 2.2.1
- Foundry VTT: 10.291
Chrome 114.0.5735.134
Opera GX LVL4 (core: 99.0.4788.75)
FireFox 114.0.2 (64-bit)

Any help would be greatly appreciated!

**Comment by jared112git** [comment]
> Same issue. One player, similar error message.

I found a workaround and might be the root cause of it. If you get your player to change this setting to: "Original Item Only" and F5. The HUD works again. If the player turns the setting back on to include macro it crashes instantly like my original example. 

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/134901291/1bb30544-2071-4aa5-bdf5-0bde548f777e)

**Comment by Larkinabout** [comment]
> Where is that setting? Token action hud core, 5e, or classic? We can't find that setting to toggle.

It's in the Token Action HUD Core module settings, but it only appears when you have the Item Macro module enabled.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.10.

**Comment by jared112git** [comment]
Thanks @Larkinabout works great!
