### ISSUE TITLE
New plugin for Token Action HUD

### ISSUE THREAD

**Issue by Zakarik** [Larkinabout/fvtt-token-action-hud-core#155]
Not really an issue, but I didn't really know how to contact you.

I've created a new plugin for Token Action HUD, I saw you listed them on your Github, if you'd like to add it like the others :
https://github.com/Zakarik/token-action-hud-mm3

It's a plugin for Mutants & Masterminds 3E

**Comment by Larkinabout** [comment]
Will do!

**Comment by Larkinabout** [comment]
Added to README and Token Action HUD Core package page.
