### ISSUE TITLE
[FEATURE] Token Action HUD for Blade Runner

### ISSUE THREAD

**Issue by mrcomac** [Larkinabout/fvtt-token-action-hud-core#160]
**Describe your idea**
I didn't see anyone working on this. Hope I didn't miss any previous work

https://github.com/mrcomac/token-action-hud-bladerunner/

**Versions**
- Token Action HUD System:token-action-hud-bladerunner
- System: Blade Runner

**Additional context**
N/A

**Comment by Larkinabout** [comment]
This module is now listed on the Token Action HUD Core readme and package page.
