### ISSUE TITLE
[BUG] Token Action Hud causes Object.mergeObject to produce an error

### ISSUE THREAD

**Issue by ByronThompson** [Larkinabout/fvtt-token-action-hud-core#162]
**Describe the bug**
When selecting a token, the following error appears in the console
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/29874212/e50cffc3-6f39-4515-9203-3fb68cc65ad9)

**Steps to reproduce**
1. Place any token onto the canvas (This specific error occurred with the "Giant Rat" Actor, but it should happen on all tokens)
2. Select the token
3. See error

**Versions:**
- Token Action HUD Core: 1.4.13
- Token Action HUD System: pf2e 1.4.9
- System: pf2e 5.1.2
- Foundry VTT: 11.304
- Browser: Opera GX 100.0.4815.44, Google Chrome 114.0.5735.199

**Additional context**
No other modules installed (Screenshot below). Error seems to be caused by the "this.position" value of the rendering application being undefined for some reason

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/29874212/6bd96e29-b6ef-4ec5-9f35-85c4fece55c1)

**Comment by Larkinabout** [comment]
Roll back to 1.4.11 until I can look into it: https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/download/1.4.11/module.json

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD 1.4.14.
