### ISSUE TITLE
[BUG] Sub menus of Token Action Hud do not close after no longer hovering

### ISSUE THREAD

**Issue by ByronThompson** [Larkinabout/fvtt-token-action-hud-core#163]
**Describe the bug**
As title. When hovering over a menu (for example "Actions") the menu does not disappear when no longer hovering. See below screenshot
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/29874212/1b77250f-5db4-4f0b-85e4-49b13cdbe289)

**Steps to reproduce**
1. Place any token onto the canvas (This specific error occurred with the "Giant Rat" Actor, but it should happen on all tokens)
2. Select the token
3. Hover over any of the available menus
4. Stop hovering over the menu. The menu does not disappear

**Versions:**
- Token Action HUD Core: 1.4.13
- Token Action HUD System: pf2e 1.4.9
- System: pf2e 5.1.2
- Foundry VTT: 11.304
- Browser: Opera GX 100.0.4815.44, Google Chrome 114.0.5735.199

**Additional context**
No other modules installed. When clicking one of the contents of the Sub menu (For example, rolling a deception check) All open sub menus may close. This does not happen every time

**Comment by strongpauly** [comment]
I see this too after upgrading to Token Action HUD Core 1.4.13.  I'm on Token Action D&D 5e: 1.4.9 and Foundry VTT: 11.305

**Comment by StefanEggenschwiler** [comment]
Just installed the module for the first time with the same issue:
- FoundryVtt v11.305
- System: DnD5e v2.2.2
- Browser: Edge v114.0.1823.82
- Token Action HUD Core v1.4.13
- Token Action HUD D&D 5e v1.4.9

**Comment by Larkinabout** [comment]
Roll back to 1.4.11 until I can look into it: https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/download/1.4.11/module.json

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD 1.4.14. Make sure to clear your browser cache.
