### ISSUE TITLE
[BUG] Hud appears over scene navigation menu.

### ISSUE THREAD

**Issue by strongpauly** [Larkinabout/fvtt-token-action-hud-core#164]
**Describe the bug**
If positioned close to the top of the screen (which it is by default) the scene navigation menu appears underneath the hud. 

**Steps to reproduce**
1. Go to any scene with a token
2. Select a token
3. Open the scene navigation menu

<img width="1098" alt="Screenshot 2023-07-14 at 09 49 10" src="https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/853954/9c769344-d53d-471a-a97e-831d2bc11371">

**Versions:**
- Token Action HUD Core: 1.4.13
- Token Action HUD System: token-action-hud-dnd5e 1.4.9
- System: dnd5e 2.2.2
- Foundry VTT: 11.305
- Browser: Electron Client

**Additional context**
 Its a minor usability issue as you can always deselect the token to access to the full menu.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.16.
