### ISSUE TITLE
Remove witdh style in tah-actions

### ISSUE THREAD

**Issue by neo2005** [Larkinabout/fvtt-token-action-hud-core#166]
**Describe your idea**
When you disable the grid option in settings, the code adds a width to the div with the tah-actions class. 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/4352954/bcb73d92-0de4-4937-9a73-0e74f32bb9fd)
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/4352954/46483562-46e1-40a8-9cc7-ce48133e0613)

If you delete that "width" the div automatically wraps to one line.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/4352954/c453d8a4-d5a7-46a7-b742-c86b3e281d38)
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/4352954/f0ae8a69-32a8-4f05-9815-bcfe5dbc8df4)

**Versions**
- Token Action HUD System:  token-action-hud
- System: pathfinder 2e

**Comment by Larkinabout** [comment]
You can set a custom width for the menu using the dialogs. Unlock the HUD and right-click on the top-level button (Looks like it's Attack in your screenshot), go to the Other Setting tab and enter a number into Custom Width. Remember to lock the HUD again afterwards.

The width on the actions element is auto-calculated to avoid long lines like the one in your screenshot, but if your preference is a single line, a custom width is the way to go.

**Comment by neo2005** [comment]
Thanks
