### ISSUE TITLE
[Bug] Versatile weapon with grid setting doesn't work

### ISSUE THREAD

**Issue by Zullock** [Larkinabout/fvtt-token-action-hud-core#167]
There is a bug where if you have any versatile weapon with the setting "Grid" from HUD Core the setting doesn't work at all.

Console log:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at CategoryResizer._getGridWidth (token-action-hud-core.min.js:1:15373)
    at async CategoryResizer.resizeCategory (token-action-hud-core.min.js:1:14408)

**Comment by Larkinabout** [comment]
Will fix for the next release, but probably best not to use the grid setting on Strikes as it doesn't work well with the widths of the buttons.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.16.
