### ISSUE TITLE
[BUG] Right-Clicking scene pops error

### ISSUE THREAD

**Issue by Aeristoka** [Larkinabout/fvtt-token-action-hud-core#168]
**Describe the bug**
Right-clicking any scene in the scene bar on top of the current scene pops the following errors:

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/7988297/17deded4-23bd-407e-ad81-de359074f342)

**Steps to reproduce**
1. Load into FoundryVTT
2. Right-click on any scene in the scene top-bar

**Versions:**
- Token Action HUD Core: 1.4.16
- Token Action HUD System: token-action-hud-pf2e-1.4.10
- System: pf2e 5.1.2
- Foundry VTT: v11.305
- Browser: Google Chrome 114.0.5735.198

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.17.
