### ISSUE TITLE
[FEATURE] Add option to ignore "Always Show HUD" for GM

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#17]
**Describe your idea**
I love the "Always Show HUD" feature for my players, so that the hud is always shown, whether they have tokens on the scene or not. As a GM however, it always keeps the hud for the last token selected on the screen. I would love to have the option to disable this behavior and only show the hud for the GM when a token is selected.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.0.2. It was a bug rather than an intended feature.

**Comment by nschoenwald** [comment]
Awesome, thanks for the quick fix!
