### ISSUE TITLE
[BUG] Console error when Show Character Name is enabled

### ISSUE THREAD

**Issue by ottyn** [Larkinabout/fvtt-token-action-hud-core#172]
**Describe the bug**
When the Show Character Name is enabled and Direction set to Auto.  If you move the HUD to the bottom of the screen it throws an error in the console on Styling.

HUD still works correctly though.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/97130150/1d951837-e157-4abc-b6e9-737e662dd0ec)

**Versions:**
- Token Action HUD Core: 1.4.16
- Token Action HUD System: PF2E 1.4.11
- System: PF2E 5.1.2
- Foundry VTT: 11.305
- Browser: Chrome 114.0.5735.199

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.17.
