### ISSUE TITLE
[FEATURE] add support for simple worldbuilding

### ISSUE THREAD

**Issue by spindocks** [Larkinabout/fvtt-token-action-hud-core#179]
When using the Simple Worldbuilding system, Token Action Hud Classic does not even appear within the "manage modules" window. Would be nice to use this module for systems that dont have one set up in foundry, or custom systems.

**Comment by mccaffertyt** [comment]
From my experience you can get Token Action HUD Core to install, but it seems to have no effect.

I have tried adding the Token Action HUD Template by downloading the zip and installing manually which also has had no effect.
