### ISSUE TITLE
[FEATURE] Copy HUD Setup to Another User

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#18]
**Describe your idea**
Add a macro to copy a HUD setup from one user to another, e.g., `copyHud(fromUser, toUser)`.

**Comment by apoapostolov** [comment]
Will it be possible to define many toUsers in a set, so I can add the whole party of players?

**Comment by Larkinabout** [comment]
Yes, you can pass an array. It's basic at the moment to fill a gap. I might expand on it later to make it easier to copy without having to grab hold of the user ids.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.1.0.
