### ISSUE TITLE
[FEATURE] Allow Action names to be displayed

### ISSUE THREAD

**Issue by ApocalypseDoggo** [Larkinabout/fvtt-token-action-hud-core#181]
**Describe your idea**
add a toggle to allow action names and their features to be fully displayed at all times instead of relying on hovering the icon. I liked the way the old versions did it and the old way can be improved by adding action tags such as reach, poison, fatal, or other action tags on NPC's. The module already does this for Players, why can't it do it for NPC's?

**Versions**
- Token Action HUD System: [Token Action HUD Pf2e]
- System: [Pf2e]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Are you able to provide screenshots as I'm not sure what you mean?

If you're referring specifically to strikes, there are module settings to hide the strike images and show the strike names by default.

**Comment by ApocalypseDoggo** [comment]
Player strike menus look like this

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/140922433/71744967-cdf9-41d3-a53e-33e5d0cc8571)

everything is nicely labeled and i only need to glance to press the right button

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/140922433/6814a889-8c3e-4a78-a855-858aeca5a653)


NPC strike menus look like this, and the only way to tell which is which is to hover and wait, which can take quite some time depending on server lag. The module already seems to be quite slow on v11 often taking a second or five to switch to new tokens so this just adds additional waiting time.

**Comment by Larkinabout** [comment]
It looks like the Show Strike Names module setting is/was disabled. If you enable it now, then either remove and re-add the Strikes group or reset the layout using the Reset Layout module setting, it should show the strike names on all actors.

**Comment by ApocalypseDoggo** [comment]
Well now i feel stupid. I didn't know that setting existed before now, it's always been enabled by default until v11 was installed. Doesn't really excuse me failing to see it the half dozen times i went looking for it or something like it though. Sorry for wasting your time
