### ISSUE TITLE
[BUG] Turning hud grid off requires refresh to take effect

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#182]
**Versions:**
- Token Action HUD Core: 1.4.16
- Token Action HUD System: pf1 latest
- Foundry VTT: 11.306
- Browser: Google Chrome 115.0.5790.110

Enabling the core Grid setting changes the hud immediately to a grid. Toggling it back off does nothing. You have to refresh the page for the grid go away

**Comment by Larkinabout** [comment]
Most likely due to changes here: https://github.com/Larkinabout/fvtt-token-action-hud-core/blob/4f71c2758bae2a7d60e172904a14b5d7fe9654be/scripts/token-action-hud.js#L90C17-L90C17

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.17.
