### ISSUE TITLE
[BUG] Updating actor with effects from token action HUD hides the "Strikes" section.

### ISSUE THREAD

**Issue by Maelorn09** [Larkinabout/fvtt-token-action-hud-core#184]
**Describe the bug**
Updating actor with effects from **locked** token action HUD hides the "Strikes" section. Only seen for NPCs. PCs are ok.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/888f4eca-f39e-4c8d-a2be-fe296609f74c)

Deselect + selecting the same token again shows the strike section:

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/713e4046-ce2d-4ace-99ce-ef63aae50afc)

Unlocked HUD doesn't have this error.

**Steps to reproduce**
1. Go to any NPC
2. Click on "effect" section in the HUD
3. Click on any effect
4. See how strike section disappears

**Versions:**
- Token Action HUD Core: 1.4.16
- Token Action HUD PF2: 1.4.13
- System: PF2 5.2.3
- Foundry VTT: 11. Stable. Build 305
- Browser: Google Chrome 115.0.5790.110

**Comment by Larkinabout** [comment]
I don't seem to be able to reproduce this issue. I have recently updated Token Action HUD Core to 1.4.17 and I am also on Foundry VTT 11.306.

Can you try updating both Token Action HUD Core and Foundry VTT and see if the issue persists?

**Comment by Maelorn09** [comment]
@Larkinabout it's fixed now after the update to 1.4.17. Thanks a lot

**Comment by Maelorn09** [comment]
@Larkinabout seems like it's still there. I just tried it with some PCs first and it seemed fine, but now I am reproducing it with other NPCs. 

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/af0cc750-46fa-4ff6-8659-264f0e5ddfdb)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/46afc55e-20d1-40f9-992d-23c59be3a53e)

**Comment by Maelorn09** [comment]
Yes, I'm on Forge. I just created a new PF2 world without any modules and managed to reproduce.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/fd36eacb-89a2-42ba-884e-f78d251f8103)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/114569560/e255b1d7-b001-4080-ada2-8f69f9b77a5b)

**Comment by Larkinabout** [comment]
Would you be able to give me temporary access to your Forge game, so I can test? You can message me on Discord @larkinabout

**Comment by Maelorn09** [comment]
Sent you a PM

**Comment by Maelorn09** [comment]
@Larkinabout solved. Now it's working fine
