### ISSUE TITLE
[BUG] Group's info1, info2, info3 not working as declared

### ISSUE THREAD

**Issue by Forien** [Larkinabout/fvtt-token-action-hud-core#186]
**Describe the bug**
`info1`, `info2` and `info3` fields are text fields and not object fields. This means there is different data structure between Groups and Actions for `info` fields and disallows to define the tooltip text for each info. 

Additionally, the System Module Development documentation says they are objects:

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/11304207/514e98c0-ad61-4ca6-8ac1-3ea284d08d33)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/11304207/7be0af43-f2bd-403e-a9ee-6ac3efc71dc6)
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/11304207/60a368d8-c740-4f5b-b08c-eb83416d9b1e)

What's more, as you can see, the `info` fields push the group's name upwards, instead of sitting on the right side.

I'm using `tab` groups .

**Steps to reproduce**
1. Make a 'tab' group
2. Add `info1 = 'test'` and `info2 = { class, text, title }` fields to it
3. Observe how info fields behave

**Versions:**
- Token Action HUD Core: 1.4.16
- System: wfrp4e 6.6.1
- Foundry VTT: 11.306
- Browser: Foundry VTT 11.306

**Comment by Larkinabout** [comment]
The object structure is correct, it just wasn't applied correctly in the template. This'll be in the next release.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.19.
