### ISSUE TITLE
[BUG] Crash due to "TypeError: y.includes is not a function"

### ISSUE THREAD

**Issue by dndcodemonkey** [Larkinabout/fvtt-token-action-hud-core#191]
Foundry VTT Version 10 Build 303
DND 5e 5th Edition System 2.3.0

1. Started World with only the two Token-Action HUD Modules and the socketlib module active#
2. Select a token

The token Action HUD is not showing up and the console throws the following error:

{code}
Uncaught (in promise) TypeError: y.includes is not a function
    #S action-handler.js:714
    #k action-handler.js:729
    addActions action-handler.js:1108
    addActions action-handler.js:1106
    #p token-action-hud-dnd5e.min.js:1
    #i token-action-hud-dnd5e.min.js:1
    buildSystemActions token-action-hud-dnd5e.min.js:1
    #h action-handler.js:207
    buildHud action-handler.js:98
    #Ct token-action-hud.js:1056
    update token-action-hud.js:994
    handleHookEvent init.js:169
    <anonymous> init.js:129
    #call foundry.js:724
    callAll foundry.js:681
    control foundry.js:25388
    _onClickLeft foundry.js:25610
    _onClickLeft foundry.js:47425
    callback foundry.js:27872
    _handleClickLeft foundry.js:28069
    _handleMouseDown foundry.js:28049
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8
{code}

I would assume it has something to do with the update of the DND 5e Game System to 2.3.o as this is, ,as I believe, the only change I made in the system.  So possibily it could affect the Token Action HUD DND Module and not this one, but I am absolutely not shure.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.11.
