### ISSUE TITLE
[BUG] 1.4.17+ causes certain module not to load

### ISSUE THREAD

**Issue by Aliharu** [Larkinabout/fvtt-token-action-hud-core#193]
Hey, I'm developer for the Exalted Third Token Action Hud module.

Recently when i start up a world the module refuses to load at all.  I dug through the version and saw it started on version 1.4.17 of Core.

I see no indication of breaking changes in the Core Changes for System devs page.

Were there undocumented potentially breaking changes in 1.4.17?

**Comment by Larkinabout** [comment]
Hi @Aliharu,

None that I'm aware of. Can you enable Debug via the Token Action HUD Core module settings and let me know what the console log says regarding Token Action HUD.

**Comment by Aliharu** [comment]
I can't even access the settings for token hud core.  They don't show up even with the module enabled.

**Comment by Larkinabout** [comment]
You should probably be getting some errors then. You might want to try reseting your browser cache to see if it's using old cached files.

**Comment by Aliharu** [comment]
0 Errors.  This happens on both my desktop and laptop.

My modules files don't even show up when i try and search their names in my console.  Its like my module doesn't exist to Token HuD core.

**Comment by Aliharu** [comment]
![Capture](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/6546285/24336e7a-e00f-448c-a15c-e08acee29b86)
Ah looks like the error was hidden

**Comment by Aliharu** [comment]
Okay so heres the issue.

I was doing an import

import { Utils } from '../../token-action-hud-core/scripts/token-action-hud-core.min.js'

In my module to use Utils.getImage(item).  It looks like its now in folder "scripts" and Utils no longer gets anything

**Comment by Aliharu** [comment]
Closing as i have solved this issue specifically.
