### ISSUE TITLE
Reset HUD error

### ISSUE THREAD

**Issue by pesky-wobbit** [Larkinabout/fvtt-token-action-hud-core#2]
In settings I get the following error when I check "Reset HUD"
![image](https://user-images.githubusercontent.com/477446/209731535-b0ea752d-0b96-491e-a483-20405416ce5c.png)

**Comment by Larkinabout** [comment]
Hi @pesky-wobbit, it looks like there are more red errors in the console, would you be able to output all the errors in full to help me investigate this issue.

Would you also be able to show me where both modules are installed on your system. You can find this in the console under the Sources > Page tab:
![image](https://user-images.githubusercontent.com/105953297/209738800-11c0fd9d-b267-406f-b655-f2f0c2ff9dd9.png)

**Comment by pesky-wobbit** [comment]
Here a snip under source tab:
![image](https://user-images.githubusercontent.com/477446/209741703-9e6744e7-9bf8-429a-891a-7760f8c3c2fa.png)

**Comment by pesky-wobbit** [comment]
There were only 2 errors. Here is another try at the reset:
![image](https://user-images.githubusercontent.com/477446/209741965-373901e2-c16a-48e7-ae24-2484e3c37d5a.png)

**Comment by Larkinabout** [comment]
Hi @pesky-wobbit, I suspect this issue will also be resolved when you update to [Token Action HUD D&D 5e 0.1.1](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/tag/0.1.1).

Let me know how you get on.

**Comment by pesky-wobbit** [comment]
Works well now. Thank you!
