### ISSUE TITLE
[FEATURE] Special Grid Mode for Conditions Tabs

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#20]
One of the areas where legacy TAH had a bit of a ergonomic issue was sections of skills and conditions where the boxes having dynamic width made it very hard to tell where a specific frequently used skill or specific condition is located. In those cases UX studies suggests fixed width grids and many Foundry mods use fixed grid with labels for conditions (Monk's Little Details can do this for both 5E and PF2)

My suggestion is to add a new fixed width grid mode that will be used for specific sections only, and can be toggled on and off from the section settings. What it does is, it sets a fixed width of each grid item, so they appear in a clear and easy to visually remember matrix (up to the default or custom width in pixels). If the text string is longer than a grid width, use "..." to cut it shorter, it will still be very recognizable by icon and first few words or 12-15 symbols.

![image](https://user-images.githubusercontent.com/4083812/215158723-f75509c6-d366-44b5-80cb-1564af9bc02a.png)

**Comment by Larkinabout** [comment]
This is one I've been trying to get right for a while as I'm not a massive fan of the mixed widths myself. I've tried fixed widths as we'll as setting standard ranges like: 50px, 75px, 100px, etc., but it's either not enough of a difference or it's too much and you get buttons with too much empty space. It's especially apparent with the button format.

Your suggestion to limit the text is a good next bet as well as a single column option in more of a standard menu format for people that just like to scroll.

**Comment by Larkinabout** [comment]
![image](https://user-images.githubusercontent.com/105953297/216785633-34569113-c1f1-4267-a220-9dc8f25dd19d.png)

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.2.0.
