### ISSUE TITLE
[BUG] TAH is blurry on mouseover

### ISSUE THREAD

**Issue by Peach774** [Larkinabout/fvtt-token-action-hud-core#201]
**Describe the bug**
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/5171184/42f43a95-b339-4dbf-b193-5d40cfa2adac)
The hud gets slightly blurry on mouseover, which is likely not the intended effect. Its rather minor, but it IS noticable

**Steps to reproduce**
1. Launch a game with the modules installed
2. Look at the token bar
3. Mouse over one of the things, and see that its blurry.

**Versions:**
- Token Action HUD Core: 1.4.20
- Token Action HUD System: token-action-hud-pf2e 1.4.15
- System: pf2e 5.6.2
- Foundry VTT: 11.311
- Browser: Foundry App

**Additional context**
This is a new issue, and still occurs with no other modules installed

**Comment by Larkinabout** [comment]
I'm not able to reproduce this issue. Does it occur with the other styles? Do you have the Dorako module enabled?

**Comment by Peach774** [comment]
> I'm not able to reproduce this issue. Does it occur with the other styles? Do you have the Dorako module enabled?
I just figured it out - its from using an alternate scale. I had my scale set to 0.95, so i made it bigger and it was still blurry, but when I set it to 1, it was no longer blurry.

I do have the dorako module and style enabled but I think the scale is the cause.
