### ISSUE TITLE
[BUG] Uncaught (in promise) Error: Directory does not exist...

### ISSUE THREAD

**Issue by Shadow-355** [Larkinabout/fvtt-token-action-hud-core#202]
**Describe the bug**
The module doesn't appear to be running properly at all and is tossing an uncaught error in the console.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/60007620/fe89f881-a08e-42d0-b8de-90b21a4ba605)

**Steps to reproduce**
1. Launch Game
2. Press F12 to open the console.
3. Click on any actor or token.

**Versions:**
- Token Action HUD Core: v1.4.20
- Token Action HUD System: D&D 5E v1.4.13
- System: DnD5E v2.3.1
- Foundry VTT: v11.313
- Browser: Brave Version 1.58.137 Cromium: 117.0.5938.153 (Official Build) (64-bit)

**Additional context**
I have already attempted Foundry with only the Core, 5E, and socketlib modules installed, but the problem still persists... I'm unsure what is causing the issue. I also attempted to use a different browser, Edge, but this also didn't work. My final attempt to fix the issue was to reinstall the modules, which didn't seem to fix it either.

I've attached the console log from that session in case that helps to diagnose the issue. The error occurs in the console at line 169.
[ActionHud Error.log](https://github.com/Larkinabout/fvtt-token-action-hud-core/files/12839841/ActionHud.Error.log)

**Comment by madseumas** [comment]
For a workaround you can try going to Foundry's settings menu (Game Settings->Configure Settings), then Token Action HUD Core, then Layouts, and "Reset All Layouts".  I _think_ I had that happen to me before and was able to get rid of the error that way.

**Comment by comsnath** [comment]
I'll give that a try and report back, thanks!

**Comment by comsnath** [comment]
That didn't seem to work, I received this error when I attempted that. The HUD still didn't display.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/60007620/40c00d9f-8470-4874-9cb6-819a113fa076)

**Comment by Shadow-355** [comment]
I managed to hotfix the issue. By creating the missing folder directories, mainly the "/Data/modules/token-action-hud-core/storage/vonkora/actor" and "/Data/modules/token-action-hud-core/storage/vonkora/user" folders, the module began working again without issue.

While this doesn't fix the odd underlying issue of the problem occurring in the first place, at least the issue can be fixed by creating those folders manually. I wonder if those folders can be automatically created to replace them in the event they are deleted in the future.

**Comment by Larkinabout** [comment]
> While this doesn't fix the odd underlying issue of the problem occurring in the first place, at least the issue can be fixed by creating those folders manually. I wonder if those folders can be automatically created to replace them in the event they are deleted in the future.

That does already happen on reload:
![token-action-hud-core-directory-creation](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/105953297/e102e4f2-6ded-40e1-9772-a7335d7daf9e)

**Comment by Shadow-355** [comment]
Strange. They weren't automatically created in my case, I'm unsure why that occurred. On the bright side, it's now working without issue now that the folders are present.
