### ISSUE TITLE
[FEATURE] New companion Token Action HUD system module for Cyberpunk RED

### ISSUE THREAD

**Issue by TheXeno30** [Larkinabout/fvtt-token-action-hud-core#213]
**Describe your idea**
making new companion Token Action HUD system module for Cyberpunk RED

**Versions**
- Token Action HUD System: None
- System: Cyberpunk RED

**Additional context**
Would very much like to have it for this system

**Comment by Larkinabout** [comment]
A request for Cyperpunk RED is already open here: #26. It needs a developer to build out the system module. Closing this issue as a duplicate.
