### ISSUE TITLE
[FEATURE] HIgher contrast headers for default theme

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#214]
One of my users was asking for the headers to be a bit more visible, here's an example they gave.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/3664822/fa7d8019-5eac-4699-a8e2-c9b51d6cf2ae)
Maybe a bigger font or just a drop shadow would help here?

Personally I'm ok with it, but I've been told by basically everyone that I keep my fonts too small so I may not be best judge for that 😅

**Comment by Larkinabout** [comment]
Tweaked the CSS in 1.5.7 to make the group headings easier to see.
