### ISSUE TITLE
Delayed token movement on each movement

### ISSUE THREAD

**Issue by xKillerbees** [Larkinabout/fvtt-token-action-hud-core#219]
Token Action HUD Pathfinder 2e - 1.5.4 
Library - Token Action HUD Core - 1.5.2
Color Picker - 1.3

It looks like on every movement it is updating, building and preparing on each space moved and when there are multuple players doing this at once, everyone complains of lag. When the Pathfinder 2e token action hud module is disabled it goes away. 

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/2941079/87749b2f-bfb3-4f7f-8f3f-cd1feed2186f)

**Comment by xKillerbees** [comment]
Any idea on when this exception will be made? Not urgent but curious when I'll be able to use both modules at the same time again.

**Comment by Larkinabout** [comment]
Fixed in 1.5.3.
