### ISSUE TITLE
[FEATURE] Option to hide empty subsections

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#22]
Probably a default functionality rather than an option, or an option turned by default. Can be global or per section (probably per section is best). Should be on by default for the Spells section in 5E.

![image](https://user-images.githubusercontent.com/4083812/215162589-5f256c00-4357-4d61-a585-395ad1decbd3.png)

**Comment by Larkinabout** [comment]
Empty subcategories are hidden while the HUD is locked. They're shown while the HUD is unlocked aka in "edit mode" to allow users to add to those subcategories. Effectively, the lock/unlock button is play mode/edit mode.

**Comment by apoapostolov** [comment]
Thanks, that explains it. I will close this proposal.
