### ISSUE TITLE
[FEATURE] Support for Cyberpunk Red 

### ISSUE THREAD

**Issue by SilverSaan** [Larkinabout/fvtt-token-action-hud-core#221]
Requesting base support for Cyberpunk Red
https://foundryvtt.com/packages/cyberpunk-red-core/

Basic Utilities, like using guns, equipping, gear selection.

**Comment by Larkinabout** [comment]
A request for Cyperpunk RED is already open here: #26. It needs a developer to build out the system module. Closing this issue as a duplicate.
