### ISSUE TITLE
[BUG] Savage Pathfinder not showing in scenes

### ISSUE THREAD

**Issue by Fritz4012** [Larkinabout/fvtt-token-action-hud-core#222]
**Describe the bug**
TAH is not appearing in scenes. in Savage Pathfinder on Foundry VTT.

**Versions:**
- Token Action HUD Core: 1.5.3
- Token Action HUD System: SWADE 0.9.3
- System: SWADE 3.2.5 + Savage Pathfinder 3.2.1
- Foundry VTT: [latest version 11+
- Browser: [e.g. Google Chrome latest]

**Additional context**
I have installed Token Action HUD Core + Token Action HUD Savage Worlds. Only Token Action HUD Core is showing in Manage Modules. The TAH does not appear in scenes at all.

**Comment by Larkinabout** [comment]
Have a look in your browser's console to see if there are any errors related to Token Action HUD. Also this may be an issue with Token Action HUD SWADE, which is supported by a different developer. You may need to raise your issue over there: https://github.com/mrcomac/token-action-hud-swade

**Comment by mrcomac** [comment]
That's odd.
it shows for me as following. Did you get any error in the console? If the error still persists, please open an issue [here](https://github.com/mrcomac/token-action-hud-swade/issues/new/choose).

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/6748594/9388465b-7c28-49da-887f-084c456df34c)
