### ISSUE TITLE
[BUG] Toggle abilities disapeared after update to Latest pf2e version 

### ISSUE THREAD

**Issue by ferositas** [Larkinabout/fvtt-token-action-hud-core#226]
**Describe the bug**
After updating to the latest version of PF2e action hud and the PF2e game system I noticed that the toggles do not display for token actors anymore.  this seems to be affecting all creature tokens players and monsters which have toggle checkboxes for abilities 

for example valeros has the feat "Double Slice" which would normally populate a Toggle named double slice second attack  which we could toggle via the Action bar this would affect the checkbox on the sheet itself. 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/1104930/ff9e3bb8-5f6a-4514-bed2-928eec309ddc)

on the action bar this used to be placed under strikes under a category named "toggle".  however since the update these toggles have gone away. 

looking at it via the edit window and looking for double slice directly only returns the feat which does not actually change the toggles on the character sheets. 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/1104930/b452c60f-930c-4b24-bc55-9a6a13be71fd)

**Versions:**
- Token Action HUD Core: 1.5.3
- Token Action HUD System: PF2e 1.5.1
- System: PF2e 5.14.2
- Foundry VTT: V11 Build 315
- Browser: reproduced in Edge  and chrome

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
If this is still an issue with the latest versions, raise an issue over here: https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues
