### ISSUE TITLE
[BUG] "Error during roll tests"

### ISSUE THREAD

**Issue by CalielBR** [Larkinabout/fvtt-token-action-hud-core#229]
Good evening,

I believe the issue is not with BR2SW, but I just wanted to report that when starting a combat, clicking to test a skill or attribute results in an error as shown in the image.

I will also pass this problem along to the developer of Action Hud Swade.

I disabled the Action Hud, and BR2SW worked normally

**Steps to reproduce**

When clicking on the selected token's abilities, it does not roll the dice (tests) for that attribute, skill, as shown in the error image.

**Versions:**
- Token Action HUD Core: [1.5.3]
- Token Action HUD System: [token-action-hud-swade 0..5]
- System: [Savage Worlds  3.3.6]
- Foundry VTT: [Version 11 build 315]
- Browser: [microsoft edge Version 122.0.2365.92 (Official Build 64-bits)]

![BR2_Swade-bug](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/101577101/0e70482c-8cf2-4d53-83dd-8fb5a621804a)

**Comment by mrcomac** [comment]
already resolved in the system hud https://github.com/mrcomac/token-action-hud-swade/issues/36
