### ISSUE TITLE
[BUG] button description

### ISSUE THREAD

**Issue by mrcomac** [Larkinabout/fvtt-token-action-hud-core#238]
**Describe the bug**
Not sure if it's a bug or i'm doing something wrong.

I'm trying to create buttons with the field description, however the description doesn't display when I let the mouse on the button, it shows the name of the button.

example:
```
{
        id:'move',
        name: "Move",
        img: "icons/skills/movement/arrow-upward-yellow.webp",
        description: "Move up to your Pace in inches, up to once per turn. You don't need to move all at once, you can split it.",
        encodedValue: ['main_action', "move"].join(delimiter)
    }
```

**Steps to reproduce**
1. Add a button with the field description (addActions within the class ActionHandler)
2. Go and let the mouse on the button
3. It shows the button name

**Versions:**
- Token Action HUD Core: 1.5.4
- Token Action HUD for Savage Worlds: 0.9.6
- System: swade 3.3.11
- Foundry VTT: 315
- Browser: Chrome

**Additional context**
i'm trying to update the hud to provide a new help menu for players. This new group of buttons will display action and free actions players can take during a combat.

**Comment by Larkinabout** [comment]
Is it because the property is `tooltip` and not `description`?

**Comment by mrcomac** [comment]
Tooltip did work,
thank you
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/6748594/56f0526f-9ad5-4278-b812-5a9a7039b865)
