### ISSUE TITLE
[BUG] Distance not calculated firing range weapon

### ISSUE THREAD

**Issue by makinava** [Larkinabout/fvtt-token-action-hud-core#239]
I'm not sure if the issue arise from this plugin .

When doing an attack with  a range weapon from the Hud the  range is not calculated (always 0). A error message is shown in the screen and in the console. "Unable to calculate distance between tokens, please use the token character sheet"

When doing the attack using the same weapon from the **character sheet** the distance is calculate correctly 

I found that the error only appears when the **link actor data flag** is enable

- Token Action HUD Classic 3.0.21
- System: Call of Cthulhu 7Th Edition 0.10.12
- Foundry VTT: v11 Build 315
- Browser: Brave [Versión 1.65.114 Chromium: 124.0.6367.60 (Build oficial) (64 bits)

**Comment by Larkinabout** [comment]
Token Action HUD Classic is no longer actively supported.
