### ISSUE TITLE
[SYSTEM] L5R 5e

### ISSUE THREAD

**Issue by EduardoBugs** [Larkinabout/fvtt-token-action-hud-core#241]
I started developing the Token Action HUD module for L5R 5e system.

It already has basic funcionality for inventory and weapons and techniques rolls, and i will be expanding on it.

The first release is avaliable at https://github.com/EduardoBugs/fvtt-token-action-hud-l5r5e/releases/latest/download/module.json, and comments and ideas are welcome!

**Comment by EduardoBugs** [comment]
It's on foundry!

https://foundryvtt.com/packages/token-action-hud-l5r5e

**Comment by Larkinabout** [comment]
I've added a link to the module TAH Core README and package page. Thanks!
