### ISSUE TITLE
[BUG] Lag when rotating tokens

### ISSUE THREAD

**Issue by Wolkei** [Larkinabout/fvtt-token-action-hud-core#246]
**Describe the bug**
Rotating a selected token causes lag for a split second as the hud updates. With debug enabled, the console looks identical to #219.

**Steps to reproduce**
1. Select a token
2. Hold shift and scroll to rotate token
3. Console is full of hud update messages and the token rotation is visibly choppy

**Versions:**
- Token Action HUD Core: 1.5.4
- Token Action HUD System: token-action-hud-dnd5e 1.5.4
- System: dnd5e 3.1.2
- Foundry VTT: 11.315
- Browser: Firefox 126.0

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.5.6.
