### ISSUE TITLE
[FEATURE] Add setting to hide hud while character sheet is open and / or layer hud behind character sheet

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#248]
**Describe your idea**
When the character sheet is opened, the token action hud overlays it, making the sheet more difficult to use. This could be improved by either hiding the hud while the sheet is open, or (if possible) layering the hud behind the character sheet.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/72390280/4e360b2e-2841-4baa-b967-c605d4a622d1)

**Comment by Larkinabout** [comment]
Not sure why you're seeing this as the character sheet should open on top of the HUD. I've just taken this video and tested in both V11 and V12:

![token-action-hud-core-window-overlap](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/105953297/106f3edc-2521-4512-9e9f-911e5d6e05fc)
