### ISSUE TITLE
[BUG] Customise Style not saved following refresh

### ISSUE THREAD

**Issue by S-North** [Larkinabout/fvtt-token-action-hud-core#254]
**Describe the bug**
HUD has transparent background.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/8228899/69120f06-8aa8-4697-8dd5-fea49091209e)

Change background to something more opaque and save.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/8228899/43da3bad-f55b-4134-aa90-9a18e7003e1b)

Style is in use.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/8228899/5c88c7f2-9810-4764-ae6d-8b02d31a3272)

Refresh page and the style is not displayed despite still being defined in the Customise Style dialogue.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/8228899/47538107-b52a-4e5c-a021-507a2ccefbab)
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/8228899/f022a95a-5c7d-4576-bd55-02c779b38fef)

**Steps to reproduce**
1. Go to Configure Settings > Token Action HUD Core > Customise Style
2. Set a visible colour for 'Background Color' and save, then save changes
3. Background of the HUD menus has the new colour
4. Refresh the page (f5)
5. The background of the HUD menu has reverted to default.
6. Go to Configure Settings > Token Action HUD Core > Customise Style. The custom 'Background Color' is still set correctly but is not being applied in the app.

**Versions:**
- Token Action HUD Core: 1.5.5
- Token Action HUD System: fvtt-token-action-hud-pf2e
- System: pf2e 6.0.4
- Foundry VTT: 12.327
- Browser: Google Chrome, Electron, Firefox

**Additional context**
I'm using pf2e Doraku, but the bug persists if this is disabled.

**Comment by Larkinabout** [comment]
Have you set the Style to Custom? It's unintentional for the background to be set unless the Style is set to Custom.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/105953297/4a1a327e-eda7-48a9-b296-f17b44e15314)

**Comment by Larkinabout** [comment]
Fixed in 1.5.7.
