### ISSUE TITLE
[BUG] Sections for Magic Items and Items with Spells no longer working in TAH Core v1.5.6

### ISSUE THREAD

**Issue by morepurplemorebetter** [Larkinabout/fvtt-token-action-hud-core#256]
**Describe the bug**
Commit 019cba05ce154ae9d9e1f3665d9cddc9ade233df made it so that my [Items with Spells ActionHandlerExtender](https://github.com/morepurplemorebetter/fvtt-items-with-spells-5e/blob/main/scripts/extensions/token-action-hud-dnd5e.js) no longer works. The same goes for the built-in [extender for the Magic Items module](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/blob/main/scripts/magic-items-extender.js) in the DnD5e TAH module. The sections are still added, but the spells aren't there.

**Steps to reproduce**
1. Update TAH core from v1.5.5 to v1.5.6
2. Select a token for a character with an item that uses either the Item with Spells or Magic Item module.
3. See in the HUD that the spells gained from either module are no longer visible in their appropriate sections.

**Versions:**
- Token Action HUD Core: v1.5.6
- Token Action HUD dnd5e: v1.5.8
- System: dnd5e v3.1.2
- Foundry VTT: v11.315

**Additional context**
If there is a way to edit my extender code to work with this change, than that is also a fine solution, but that would have to be applied to the extender for the Magic Items module as well.

**Comment by gioppoluca** [comment]
Is possible to have this chosen in a setting and applied automatically without having to edit HUD?

**Comment by gioppoluca** [comment]
Also after editing the newly created "magicItems" element disappears

**Comment by Larkinabout** [comment]
Fixed in 1.5.7.
