### ISSUE TITLE
[FEATURE] Add custom actions

### ISSUE THREAD

**Issue by david-a-rivera** [Larkinabout/fvtt-token-action-hud-core#259]
**Describe your idea**
I would like to be able to add actions to the HUD. For example, I am using the SWADE plugin. This allows me to add additional stats to the character sheet. This stat is something that will increase and decrease through game play. I would like to be able to add 2 additional actions to the hud to spend this new resource and to gain this new resource, much like you can with bennies.

**Versions**
- Token Action HUD System: token-action-hud-swade]\
- System: Savage Worlds

**Additional context**
That's it. Maybe add a dialog that allows you to select the stat or enter its id type of action, and any dice that are involved. Like for the above I'd like to toss a dc (from dice so nice) on the table when spent or added like bennies.

**Comment by Larkinabout** [comment]
It might be worth raising an issue over on the Token Action HUD for Savage Worlds GitHub as if these stats are created in the character sheet, it might be able to automatically pick them up. You can also add macros to the HUD to do custom actions.

**Comment by david-a-rivera** [comment]
can you? How? Macro would work for what I need.

**Comment by Larkinabout** [comment]
Unlock the HUD, right-click and group, search for the macro and add it:
![image](https://github.com/user-attachments/assets/72606fe9-9fe7-4f07-918a-a2447df33509)

**Comment by david-a-rivera** [comment]
Holy crap. I should have started here. Spent the past week trying to hook into the creation of the hud and inject my manager and action handler that wrapped swades. All that so I could do what this does.

Thank you.
