### ISSUE TITLE
[QUESTION] D&D5e, is it possible to add custom conditions?

### ISSUE THREAD

**Issue by therockisgood** [Larkinabout/fvtt-token-action-hud-core#269]
Hi, me and my players love using the token action HUD in our game. I'm introducing some variant weapon actions soon, and some of them inflict conditions that don't exist in core D&D, i.e. "maimed". I've looked in the section of the docs about adding an action, but the example shown doesn't help in my case.
The existing conditions seem to link to the appendix of the SRD compendium, but I'm not sure how to establish a link like that for custom conditions. 
Any help would be much appreciated, I'd love to have toggleable conditions for these new ones, to help with player confusion.

**Comment by Larkinabout** [comment]
Token Action HUD displays conditions that exist in the dnd5e config, but it doesn't create its own. You'd want a module that allows you to add Conditions, such as: [Custom D&D 5e](https://foundryvtt.com/packages/custom-dnd5e)
