### ISSUE TITLE
[BUG] Layout is reset after updating to 2.0.1 and can't set layout again

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#275]
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/b4319a81-199e-4e4c-829b-6c64188b8f1d">

**Versions:**
- Token Action HUD Core: 2.0.1
- Token Action HUD System: dnd5e 2.0.1
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by Larkinabout** [comment]
That's me renaming things. I'll fix for the next release but it'll be a little while as it's sleep time here.

**Comment by Larkinabout** [comment]
Fixed in 2.0.2.
