### ISSUE TITLE
Token action Hud Coriolis requirements issue

### ISSUE THREAD

**Issue by kbender84** [Larkinabout/fvtt-token-action-hud-core#276]
Hi,
I'm developer of the Token Action Hud for Coriolis.
I've tried to update the requirement for my module, to test and rollout it with TAH Core 2.0.1 (ok, 2.0.2 now), but keep geeting 
_The installed Token Action HUD system module requires Token Action HUD Core module version 1.5. Install the required version to continue using Token Action HUD._

I've updated the requirements in module.json to:
   _"requires": 
        [
          {
            "id": "token-action-hud-core",
            "type": "module",
            "compatibility": {
            "minimum": "2.0.0",
            "maximum": "2.0.99",
            "verified": "2.0.0"
            }          
          }
        ]_

Any hint what I could have missed?

I am using  both RollHandler and encodedValue in my code, should I rewrite it?

_CoriolisRollHandler = class CoriolisRollHandler extends coreModule.api.RollHandler {_
        handleActionClick(event, encodedValue) {

**Comment by Larkinabout** [comment]
Change '1.5' to '2.0' in this line: https://github.com/kbender84/token-action-hud-coriolis/blob/26c1f0bab8f74bfeaf80e405a711253843105319/scripts/module.js#L1332

**Comment by kbender84** [comment]
Thanks, now I feel stupid for not noticing this line 
It throws this now:
Uncaught (in promise) TypeError: A.doRegisterSettings is not a function
    registerSettingsCore settings.mjs:427
 and I believe registerCustomStyleSettings is TAH core.

**Comment by Larkinabout** [comment]
It's just `registerSettings` now. It was deprecated for a few versions, but I removed it in this release.

**Comment by kbender84** [comment]
In my Module I  extend SystemManager class

CoriolisSystemManager = class CoriolisSystemManager extends coreModule.api.SystemManager {

But the override for registerSettings was commented out, so it is trying to get it from core module and crashes (I'm not calling this function on my side anywhere)
        /** @override */
        /*doRegisterSettings (updateFunc) {
            systemSettings.register(updateFunc)
        }*/

I think you are still calling it in settings.mjs
registerCustomStyleSettings();

  if (systemManager.registerSettings.toString().slice(-2) !== "{}") {
    systemManager.registerSettings(onChangeFunction);
  } else {
    globalThis.logger.warn("Token Action HUD | SystemHandler.doRegisterSettings is deprecated. Use SystemHandler.registerSettings");
    systemManager.**doRegisterSettings**(onChangeFunction);
  }

**Comment by Larkinabout** [comment]
Yeah, you're right. I hadn't spotted it as the system module I tested does call it. I'll fix for the next release. If you get to it before me on your side, you can call `registerSettings` and just put anything inside the function like `return false;`.

**Comment by Larkinabout** [comment]
`doRegisterSettings` error should be fixed with 2.0.3.

**Comment by afolivieri** [comment]
I am getting the same error using HUD for WFRP 4E 2.1.2, and Core 2.0.3, just an heads up.

**Comment by Larkinabout** [comment]
> I am getting the same error using HUD for WFRP 4E 2.1.2, and Core 2.0.3, just an heads up.

If it's the first error about required version, you'll need to revert back to Token Action HUD Core 1.5.7 and wait for the Token Action HUD for WFRP 4E to be updated.

**Comment by kbender84** [comment]
Thanks for the update yesterday. 
I get bunch of new errors now. 
Actualy I am thinking about locking the module for now with TAH 1.5.7 AND rewriting the code for 2.03,

**Comment by Larkinabout** [comment]
If you're getting errors, it may be something that needs adding/fixing with Token Action HUD Core. I expected the methods used by Token Action HUD system modules to be unaffected.

**Comment by Larkinabout** [comment]
If you want to push your current code, I'll take a look?

**Comment by Larkinabout** [comment]
I've submitted a PR.

**Comment by kbender84** [comment]
Thanks a lot for fixing my code !

I've pulled it and tested - seems to work fine on my end, I'll check with few users and confirm.

**Comment by kbender84** [comment]
All works, thank you.

Please consider adding the list of updated functions to the document
https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Core-Changes-for-System-Module-Developers#token-action-hud-core-200


When updating your module to TAH Core 2.0, you must update depreciated methods,
old method -> replace it with new method

**doGetActionHandler -> getActionHandler 
doGetRollHandler  - > getRollHandler 
doRegisterSettings  -> registerSettings 
doRegisterDefaultFlags -> registerDefaults**
