### ISSUE TITLE
[BUG] actorId undefined error

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#277]
**Describe the bug**
An error is produced after an action has been performed. This is using token-action-hud-cyphersystem which I'm updating to HUD core 2.0.3.

`this.hud.actorId` is undefined, it should probably be `this.hudManager.hud.actorId`

![image](https://github.com/user-attachments/assets/c1b4e2f4-d807-46c0-ae8a-385eca709a79)

**Steps to reproduce**

**Versions:**
- Token Action HUD Core: 2.0.3
- Token Action HUD System: token-action-hud-cyphersystem latest
- System: cyphersystem 3.2.1
- Foundry VTT: 12.331
- Browser: Chrome 130.0.6723.70

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in 2.0.4.
