### ISSUE TITLE
[SYSTEM] Old School Essentials

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#28]
**Describe your idea**
Add support for the Old School Essentials system.

**Additional context**
If anyone would like to develop this Token Action HUD system module, please let me know. System modules can be developed in your own repos. See [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) for reference.

**Comment by amir-arad** [comment]
Hi

I'm a veteran JS dev, just discovered FVTT a few days ago and assembling my OSE modules stack. 
If you're willing show me the ropes I would like to implement the OSE system.

**Comment by Larkinabout** [comment]
Hi @amir-arad, that's great! You might start with this documentation: [Developing a System Module](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module) and if you are on Discord, send me a DM: Russell#7071.

**Comment by mrcomac** [comment]
is there any progress on this HUD?

**Comment by Larkinabout** [comment]
I've not heard anything.

**Comment by amir-arad** [comment]
yeah, sorry, did not get to it :(

**Comment by mrcomac** [comment]
https://foundryvtt.com/packages/token-action-hud-ose
