### ISSUE TITLE
[BUG] not positioned correctly by default

### ISSUE THREAD

**Issue by BrandonG777** [Larkinabout/fvtt-token-action-hud-core#280]
After upgrading to version 2.0.4 my menus are showing up too far up and to the left. See screenshot.
![image](https://github.com/user-attachments/assets/13161fcc-c24d-4925-a2ee-649666e2c0ce)

**Steps to reproduce**
1. upgrade to 2.0.4? Not exactly sure but it is consistent across multiple PCs.

**Versions:**
- Token Action HUD Core: 2.0.4
- Token Action HUD System: token-action-hud-dnd5e 2.0.1]
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Microsoft Edge Version 130.0.2849.56 (Official build) (64-bit)

adjusting the setting to allow dragging the positioning allowed me to correct the issue.

**Comment by jendave** [comment]
I get this too. It happens on D&D and Twodsix (Traveller) systems.

**Comment by HoelFarabee** [comment]
Can also confirm it happens on PF2e. Firefox and Google Chrome.

**Comment by Gallumph** [comment]
Seeing it on D&D 5e as well.

**Comment by Larkinabout** [comment]
Fixed in 2.0.6.

**Comment by jendave** [comment]
Confirmed. Fix works better for me
