### ISSUE TITLE
[BUG] Token Action HUD PF2e no longer working with latest Token Action HUD Core

### ISSUE THREAD

**Issue by ceallach66** [Larkinabout/fvtt-token-action-hud-core#281]
**Describe the bug**
For the last several days, I was getting an error that the PF2e module required the Core module 1.5 and won't load. Up until this point, I have been regularly updating all of my libraries and never ran into this before.

**Steps to reproduce**
1. Upgrade to latest HUD Core and HUD PF2e libraries
2. Enter PF2e world
3. See error

**Versions:**
- Token Action HUD Core: Latest (2.?)
- Token Action HUD System: PF2e 1.5.18
- System: PF2e
- Foundry VTT: 12.331
- Browser: Google Chrome Version 130.0.6723.70

**Additional context**
Someone on Discord suggested I downgrade the HUD Core to version 1.5 (exactly), so I have done that and now it is working. But I have to imagine there have been other Core versions between 1.5 and the latest version (2.?), but I've never run into this error before. Why would it suddenly give an error?

**Comment by Larkinabout** [comment]
Token Action HUD system modules are not required to support every version of Token Action HUD Core and they are not developed and maintained by the same person. If one module decides to support an earlier version of Token Action HUD Core only and forever, then they can.

I previously developed the module but as I don't play Pathfinder 2, I found the upkeep required with the system's release schedule and breaking changes difficult to maintain. It's important to remember that maintenance of these modules is voluntary and no one is being paid to upkeep them. They may work for your current setup, but there's no guarantee they will continue to work if you change your setup, such as by updating.

If you enjoy updating often, I'd suggest checking the release logs for your modules before clicking update all. This includes system releases as they often include changes that break modules such as Token Action HUD Pathfinder 2e. Alternatively, you might prefer a HUD module from a very active developer in the Pathfinder 2 community as it's more likely to keep in sync with system updates and also doesnt rely on a system-agnostic library: https://foundryvtt.com/packages/pf2e-hud

**Comment by qcdompaq** [comment]
I also have that sudden same issue. All was working well last week.

**Comment by Larkinabout** [comment]
See Token Action HUD Pathfinder 2 2.0.0.
