### ISSUE TITLE
[FEATURE] Add setting to disable collapsing sections

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#285]
**Describe your idea**
I never need to collapse the sections in my Token Action HUD. The fact that clicking on section header collapses them only adds potential misclicks for me. I would love a global setting to disable collapsing section when clicking the section headers.

**Comment by Larkinabout** [comment]
Added in 2.0.8.

**Comment by nschoenwald** [comment]
Thank you so much!
