### ISSUE TITLE
[FEATURE] Token Action HUD for Everyday Heroes

### ISSUE THREAD

**Issue by dolonite** [Larkinabout/fvtt-token-action-hud-core#286]
**Describe your idea**
Token Action HUD for Everyday Heroes 

**Versions**
- Token Action HUD System: [e.g. token-action-hud-everyday-heroes]
- System: [Everyday Heroes]

**Comment by MadBlue2112** [comment]
I've requested this a few times. I really hope there's someone who would be willing to work on this, as it's quite a good system, and Token Action HUD is a must-have module, IMHO.

**Comment by Larkinabout** [comment]
Issue for this system already exists here: #91
