### ISSUE TITLE
[SYSTEM] Dungeon Crawl Classics

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#29]
Describe your idea
Add support for the Dungeon Crawl Classics system.

Additional context
If anyone would like to develop this Token Action HUD system module, please let me know. System modules can be developed in your own repos. See [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) for reference

**Comment by madseumas** [comment]
https://foundryvtt.com/packages/token-action-hud-dcc

**Comment by madseumas** [comment]
Pinging again here - I've created a DCC Token Action HUD module located at the above spot.

**Comment by Larkinabout** [comment]
Added to the link to the Token Action HUD Core readme and package page. Many thanks!
