### ISSUE TITLE
[BUG] All empty sessions visible

### ISSUE THREAD

**Issue by lucaspicerni** [Larkinabout/fvtt-token-action-hud-core#293]
**Describe the bug**
When "enable customization" is disabled, in core, TAH D&D5 leaves all empty sessions visible.

![image](https://github.com/user-attachments/assets/82af264d-e6c3-4d91-8d6b-5afe6cac01b0)

**Steps to reproduce**
1. New World
2. Enable modules
3. Configure module

**Versions:**
- Token Action HUD Core: 2.0.7
- Token Action HUD System: 2.0.2
- System: dnd5e 4.1.1
- Foundry VTT: 12.331
- Browser: Google Chrome 131.0.6778.69

**Comment by Larkinabout** [comment]
Fixed in 2.0.9.
