### ISSUE TITLE
[BUG] Group buttons Log Console Errors

### ISSUE THREAD

**Issue by Katalyst8095** [Larkinabout/fvtt-token-action-hud-core#294]
Any time the Group buttons are opened the console logs an error: 
Uncaught TypeError: Cannot read properties of null (reading 'bottom')

![group-resizer](https://github.com/user-attachments/assets/654bd980-0aea-498c-9883-29311ff3173f)

**Steps to reproduce**
1. With Token Action Hud Core and 5e installed
2. Open a Group by either the hover or click option (both trigger the error)
3. Error appears in console for every button
4. Initially produced in a Molten hosted world, replicated in a new local world

**Versions:**
- Token Action HUD Core: 2.0.9
- Token Action HUD System: token-action-hud-dnd5e 2.0.2
- System: dnd5e 4.1.2
- Foundry VTT: 12.331
- Browser: Chrome 131.0.6778.86, or Native windows app

**Comment by jendave** [comment]
I am seeing this too. I am using the Ironsworn/Starforged System

Steps to reproduce

With Token Action Hud Core and Token Action HUD Ironsworn installed
Open a Group by hover option
Error appears in console for every button in a new local world

Versions:

FoundryVTT: 12 build 331
Token Action HUD Core: 2.0.9
Token Action HUD System: token-action-hud-ironsworn 1.0.13
System: foundry-ironsworn 1.24.8
Foundry VTT: 12.331
Browser: Chrome 131.0.6778.86, or Native windows app

**Comment by Larkinabout** [comment]
Fixed in 2.0.10.

**Comment by jendave** [comment]
Looks great. I no longer see the error. Thanks!
