### ISSUE TITLE
[FEATURE] Use Hooks for Registering System Module

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#32]
**Describe your idea**
Use Foundry VTT's Hooks mechanism to allow Token Action HUD system modules to register with the Token Action HUD Core module, e.g., `Hooks.once('token-action-hud-register', (core) => core.register(myVersionData, mySystemManager))`

**Versions**
- Token Action HUD Module: [token-action-hud-core 1.0.2]

**Additional context**
There are three main interactions to include when implementing a hook method:

1. Token Action HUD Core currently checks the module version required by the system module via a dynamic import of a file on the system module side. Compatibility data does not seem to be currently available in the module data held by Foundry VTT.
2. Token Action HUD Core uses the system module's SystemManager class to override its own class methods.
3. Token Action HUD system modules extend core classes and use a utility class for various functions. These could be passed back to the system module via a hook or made available under `game.tokenActionHud` instead.

**Comment by Larkinabout** [comment]
Partially added in Token Action HUD Core 1.1.0.

The following code example calls the hook Token Action HUD Core waits for and passes the required core module version and SystemManager class:
```
Hooks.once('ready', async () => {
    const module = game.modules.get(MODULE.ID)
    module.api = {
        requiredCoreModuleVersion: REQUIRED_CORE_MODULE_VERSION,
        SystemManager
    }
    Hooks.call('tokenActionHudSystemReady', module)
})
```
Dynamic imports of Token Action HUD Core classes into the Token Action HUD system module are still required due to the unknown order modules are loaded. If anyone has a better solution for this, please let me know. Here is the current method and required classes:
```
const coreModulePath = '../../token-action-hud-core/scripts/token-action-hud-core.min.js'
const coreModule = await import(coreModulePath)
export const CoreActionHandler = coreModule.ActionHandler
export const CoreActionListExtender = coreModule.ActionListExtender
export const CoreCategoryManager = coreModule.CategoryManager
export const CorePreRollHandler = coreModule.PreRollHandler
export const CoreRollHandler = coreModule.RollHandler
export const CoreSystemManager = coreModule.SystemManager
export const CoreUtils = coreModule.Utils
export const Logger = coreModule.Logger
```

**Comment by farling42** [comment]
You could make these available directly from one of the global objects within Foundry. For my PDF Pager module, I make some functions available as `ui.pdfpager.<functionname>`.  In your core module you could do:

```js
ui.tokenactionhud.ActionHandler = ActionHandler;
ui.tokenactionhud.ActionListExtender = ActionListExtender;
etc...
```

It might(?) then be possible to do
```js
   class MyClass extends ui.tokenactionhud.CategoryManager {
   }
``` 
I'm not 100% if the above works, otherwise something like?
```js
const CoreCategoryManager = ui.tokenactionhud.CategoryManager;
   class MyClass extends CoreCategoryManager {
   }
```

**Comment by Larkinabout** [comment]
There's also the possibility of setting core up as a library module as I believe they are guaranteed to load beforehand to make them available to non-library modules. Although I've avoided that route because I don't think TAH Core is really a library in the strictest sense.

**Comment by farling42** [comment]
Well, it is a library in that it doesn't work alone, and provides functionality to the system specific module.

**Comment by Larkinabout** [comment]
Good point. I'll explore the option.

**Comment by farling42** [comment]
Not rolling up your course module into a minified version would also help with debugging. Is your module big enough to deserve filling up?

**Comment by Larkinabout** [comment]
Yes, there are noticeable improvements for slower machines when clicking between tokens. At some point I'd like to look at focussed updating, which may mitigate the need, but that's quite a big task.

If I can get these core classes available by a global object, it'll be easy enough to make a non-minified version available for system module developers to use. It's what I use currently for development by switching out the esmodule reference to `./scripts/init.js`. It's just that it currently also requires referencing those core classes on the system module side.

**Comment by Larkinabout** [comment]
Added the `tokenActionHudCoreApiReady` hook in Token Action HUD Core 1.3.0 to provide TAH system modules with TAH Core classes without the need to import them. See [Core Changes for System Module Developers](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Core-Changes-for-System-Module-Developers) for details.
