### ISSUE TITLE
[BUG] Customising categories removes selected images from all categories

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-core#37]
**Steps to reproduce**
1. Add images to categories
2. Remove one category via customise category 

**Versions:**
- Token Action HUD Core: current
- Token Action HUD System: current
- System: dnd5e current
- Foundry VTT: current
- Browser: current Google Chrome

**Comment by apoapostolov** [comment]
Came to report this, as well.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.1.1.

**Comment by nschoenwald** [comment]
Thanks a lot for the quick fix! Love this module, makes things so much easier for my players and me.
