### ISSUE TITLE
[FEATURE] Simple automatic direction flow choice (optional, on by default)

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#39]
Instead of choosing your direction flow (up or down) it will help players who are not used to Settings pane or who change browsers often and lose the cookie, if there was an automated way to choose direction based on distance to upper and bottom corners.

If within the bottom 1/3 to 1/4 of the screen, flow up. If within the top 1/3 to 1/4 of the screen, flow down.

The middle position that very few people use, it chooses what is set in the settings or the default if not changed by player.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.3.0.
