### ISSUE TITLE
[BUG] HUD does not appear in the electron app (Chrome v94)

### ISSUE THREAD

**Issue by CeaneC** [Larkinabout/fvtt-token-action-hud-core#4]
**Describe the bug**
The Token Action HUD does not appear when using the electron app, and logs the following error in the console when you click on a token:

![image](https://user-images.githubusercontent.com/43473593/210203200-c58890ee-5fb5-4b90-8cb9-dde66aaa6e40.png)

**Steps to reproduce**
1. Run Foundry using the Electron app
2. Place a token in a scene
3. Click on the token
4. Note that the HUD does not appear, and the above error is logged in the console.

**Versions:**
- Token Action HUD Core: 0.1.1
- Token Action HUD System: token-action-hud-dnd5e 0.1.2
- System: dnd5e 2.0.3
- Foundry VTT: 10.291
- Browser: Chrome **94.0.4606.81**

**Additional context**
When launching Chrome version 108.0.0.0, the HUD appears fine; but when running through the Foundry electron app which is back on v94 the HUD doesn't appear at all and throws the above error in the console.

**Comment by Larkinabout** [comment]
Hi @CeaneC, you may need to update your Foundry VTT install to update the Electron version. I test test via module all the time via the Foundry VTT browser and although it's not the latest Electron build, it is up-to-date enough to recognise the structuredClone function.

**Comment by Larkinabout** [comment]
By update, I mean redownload and reinstall rather than updating from within the app. Make sure to back up your data beforehand.

**Comment by CeaneC** [comment]
Yep, an update via reinstall fixed it. Sorry for the false alarm, didn't realise I'd missed the memo on a new electron version
