### ISSUE TITLE
[BUG] cyphersystem displays token name, but no menu

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#40]
I've got as far as I can by examining the dnd5e implementation, but I can't see what is wrong, and no errors or warnings are being generated by the core module.

I've uploaded my code to github at https://github.com/farling42/token-action-hud-cyphersystem 

Could you provide any pointers as to why I'm not getting any HUD menu and just the title?

**Comment by Larkinabout** [comment]
I've put a pull request through with a few minor changes.
