### ISSUE TITLE
How should a checkable/selectable item be initialised?

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#41]
I have some entries which I want to show if they are selected or not.

What field needs adding to the action that I create?

I can see a "selected" field being set, but it doesn't change how anything is displayed in the HUD.

**Comment by Larkinabout** [comment]
The selected flag is to track actions that are added/removed by the user.

If I'm understanding correctly, it's the 'toggle' and 'active' classes t css class that you'll want to add to the action.

**Comment by Larkinabout** [comment]
The selected flag is to track actions added/removed by the user.

If I'm understanding correctly, you'll want to add the 'toggle' class to the cssClass property of the action and add 'active' class when the action is selected/toggled on.

**Comment by Larkinabout** [comment]
Here's an example from the D&D 5e code:

```js
const active = this.actors.every((actor) => {
                const effects = actor.effects
                return effects
                    .map((effect) => effect.flags?.core?.statusId)
                    .some((statusId) => statusId === id)
            })
                ? ' active'
                : ''
            const cssClass = `toggle${active}`
```

**Comment by farling42** [comment]
Which file is the dnd5e extract from? So that I can see it in more context.

**Comment by Larkinabout** [comment]
That one is from the `_buildConditions` method in action-handler.js.

**Comment by Larkinabout** [comment]
'toggle' and 'active' are separate css classes, so you'll need to put a space between them.
