### ISSUE TITLE
[FEATURE] Add Cypher System to the Foundryvtt page.

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#42]
My module has been approved and is listed on the Foundry VTT module listing now. Perhaps it can be added to the list of supported modules on the core page?

https://foundryvtt.com/packages/token-action-hud-cyphersystem

**Comment by Larkinabout** [comment]
Added to the [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core) page.
