### ISSUE TITLE
[BUG] 'Display Icons' setting doesn't work

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#43]
Regardless of whether "Display Icons" is selected in the HUD Core settings, the icons are ALWAYS displayed.

**Comment by Larkinabout** [comment]
You'll need to use the `getImage()` from core's Utils class or check the core ActionHandler's `this.displayIcons` value in your code when setting the `img` variable against the action.

**Comment by farling42** [comment]
Why isn't this done in core?
I've seen that the dnd5e doesn't do any special handling, it just always sets the img field of the action to the img from the item.

**Comment by Larkinabout** [comment]
Mostly a carry over from the original Token Action HUD, but I can also see the benefit of stopping the image ever being added at creation. I'd probably still do it this way if I was handling all the TAH system modules. D&D 5e should be using `getImage()`, which does the handling, though I've just spotted a place where it doesn't.

As it's a core module setting it would probably be worth moving it to a core process in the future. For now, using `getImage()` will do the job.
