### ISSUE TITLE
[BUG] Menu remains open when menu re-opens

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#45]
With the option 'Click to Open Categories' selected, if I open one of the categories and then click away from the token, the HUD disappears (correct).

But when I select a different token, the HUD opens, and the previously selected category is already visible.

I would expect the HUD to return to all categories being closed when the HUD disappears from the screen.

(Note that if the HUD is open and I click on a different Actor, then leaving the existing category open is OK since the HUD remains on display.)

**Comment by Larkinabout** [comment]
I quite like it that way, but I can see the general expectation would be for the category to close between the HUD closing and reopening.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.2.0.
