### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#46]
When the menu is open using the 'Click to Open Categories', clicking anywhere on the canvas that is also within the horizontal band containing the open menu, I can't select a new token or click on the canvas to close the HUD.

This is the full horizontal band, even far to the right of the open menus.

![image](https://user-images.githubusercontent.com/17485384/217547139-d11ca71f-5eb8-4818-9695-da1af0845272.png)

e.g. in the above picture, I can't select the bob2 or Torah tokens, or click on the canvas between those two tokens (or to the right of the bob2 token) in order to close the HUD.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.2.0.
