### ISSUE TITLE
[BUG] Unable to create subcategories for custom categories

### ISSUE THREAD

**Issue by MrPotatoZed** [Larkinabout/fvtt-token-action-hud-core#47]
I'm presuming this is a bug but I might be misunderstanding how categories/subcategories are supposed to work. I'm trying to create categories for "actions", "bonus actions", "reactions", and "other actions" to mimic how the hud used to work along with character actions list 5e but am running into problems . Right clicking on one of the existing categories brings up the subcategories interface as I presume it's supposed to. However, when I create a new category right clicking on the new category does not bring up the subcategories interface. There are no relevant errors in console. 

Video below:
![hudcore](https://user-images.githubusercontent.com/85974617/216848095-69891d68-3b91-4dc7-8ad5-f2112783602a.gif)

Also, is it possible for me to set up the hud with custom categories/subcategories for my players? I used to have them click "group by action type" in settings to ensure we were seeing the same stuff. Do I now need to talk the players through the process of setting up categories or is it possible for me to sign onto their accounts and make hud changes that they'll see when they sign in? 

**Versions:**
- Token Action HUD Core: 1.1.1
- Token Action HUD System: token-action-hud-dnd5e 1.1.0
- System: dnd5e 2.1.4
- Foundry VTT: 10.291
- Browser: Chrome 109.0.5414.120 and firefox

Thanks for taking a look at this and for all your work on this super useful mod.

**Comment by MrPotatoZed** [comment]
Thanks for the upcoming fix and for the macro!

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.2.0.
