### ISSUE TITLE
[BUG] Documentation Issues

### ISSUE THREAD

**Issue by farling42** [Larkinabout/fvtt-token-action-hud-core#52]
- The actions for addActionsToActionList is missing information about the 'img' property.

- The document for `doRenderItem` doesn't mention that the action's name must be "itemMacro" in order for this to work.

- The documentation for `getImage` doesn't mention that it only returns the image if the HUD Core option `Display Icons` is selected.

- The section `Import Token Action HUD Core Classes Example` would look better if it used JS like:
```js
import { ActionHandler, CategoryManager, RollHandler, SystemManager, Utils } from '../../token-action-hud-core/scripts/token-action-hud-core.min.js'
```

- The 'delimiter property is missing from the description of ActionHandler class. It would be good if this value was also available in the RollHandler class (for use by encodedValue.split(...)).

**Comment by farling42** [comment]
Also the description of using `tokenActionHudSystemReady` might be better by describing it as:

- A call of the tokenActionHudSystemReady hook to pass  its SystemManager class and its required core module version to TAH Core.

**Comment by Larkinabout** [comment]
> * The document for `doRenderItem` doesn't mention that the action's name must be "itemMacro" in order for this to work.

All good, I think, apart from this quoted one, which I don't understand. "itemMacro" is used in reference to the Item Macro module when building and handling its actions, but shouldn't go anywhere near the `doRenderItem` method. `doRenderItem` uses the item object to render its sheet.

**Comment by farling42** [comment]
> > * The document for `doRenderItem` doesn't mention that the action's name must be "itemMacro" in order for this to work.
> 
> All good, I think, apart from this quoted one, which I don't understand. "itemMacro" is used in reference to the Item Macro module when building and handling its actions, but shouldn't go anywhere near the `doRenderItem` method. `doRenderItem` uses the item object to render its sheet.

That comment is based on looking at the code in HUD Core. It checks for a value of "itemMacro" before calling doRenderItem (in the PreRollHandler class?).

**Comment by Larkinabout** [comment]
Ah, okay, that pre-roll handler is just for handling the Item Macro actions.

I'm not sure if there would be a good way of handling rendering of the item sheet in TAH Core as the encodedValue is defined by the system module and could be in any format.

**Comment by Larkinabout** [comment]
Think these are all resolved now.
