### ISSUE TITLE
[FEATURE] Allow TAH System Modules to Add HUD Styles

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#54]
Just an idea inspired by your PF2 CSS system, it might be more logical to bundle CSS themes with system plugins instead of the core, and allow systems to have one or multiple themes that they can register with the core.

**Comment by Larkinabout** [comment]
I have thought about this functionality, but I also really like the idea of making the styles available to everyone regardless of the system, so a user can choose a sci-fi themed HUD in a fantasy game if that's what they like. I'll probably still implement the feature in the future, but I'd also encourage any designers to build out a style and I'll add it to core for everyone to enjoy.

**Comment by apoapostolov** [comment]
That makes sense, it might be best for everyone this way.

**Comment by Larkinabout** [comment]
Added in 1.5.0.
