### ISSUE TITLE
[BUG] order of subsections in the section settings tag list seems to be reversed.

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#59]
Logically, in the multi-tag field of a section settings, the first subsection should be on the top, and the second should be below it.  Instead, the first tag is always above the second. 

This might be because I use a tab at the bottom with bottom-up opening. Maybe for that mode of opening the ordering should be shown as reversed.

**Comment by Larkinabout** [comment]
Can you screenshot an example for me please?

**Comment by apoapostolov** [comment]
Sure.

![image](https://user-images.githubusercontent.com/4083812/218344286-16290819-56c6-4066-a9d4-7f38a2b7bd25.png)

Logically Toggles and then Strikes would put Toggles on the Top, Strikes below it... instead the order starts from the bar and goes up, in reverse order. This makes it hard for the player to control the order of subsections if the ordering changes between direction of display.

**Comment by Larkinabout** [comment]
The order is intentionally flipped around when the HUD is expanding up because the first item in the list should be the most accessible in either case, i.e., the one closest to the cursor when you hover over the category. For a HUD that expands down, that's the top of list, for a HUD that expands up, that's the bottom. Effectively, the order is in most important to least important or most used to least used, not top to bottom.

**Comment by apoapostolov** [comment]
That is what I thought as well, but it is confusing since when a player moves it from flow-down to flow-up they must also reorder each of their subsections rather than the mod automatically recognizing the change (this can be related to https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/39 ). It should be fairly easy to implement both #39 and change of flow order when using flow-up.

**Comment by Larkinabout** [comment]
The expand up is actually intentionally changed for the reasons I stated in my previous comment. I don't, for example, want my weapons to end up at the end of the list and the furthest away from my cursor when I have the HUD expanding up. Likewise for spells, I want my cantrips closest to my cursor first and my level 9 spells, that I will use least often, furthest away. This feels like the best default behaviour. If it was the other way, and as I understand you're suggesting, I would constantly need to move my cursor to the very top of the screen to access my cantrips.

**Comment by Larkinabout** [comment]
Are you happy for me to close this one down as sufficiently answered?

**Comment by apoapostolov** [comment]
Yes, perfectly. Thanks for being patient and thorough with me.
