### ISSUE TITLE
[FEATURE] Equip/unequip via Token Action HUD

### ISSUE THREAD

**Issue by rpganalyst** [Larkinabout/fvtt-token-action-hud-core#60]
**Describe your idea**
I think Token Action HUD would be a better tool to manage equipment during a game session than the Actor Sheet. Being able to equip/unequip would be a very good enhancement.

Thank you.

**Versions**
- Token Action HUD System: [token-action-hud-dnd5e]
- System: [dnd5e]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Duplicate of Larkinabout/fvtt-token-action-hud-dnd5e#11. Linking your comments over to that one.
