### ISSUE TITLE
+ and - buttons for slots have issues with minimal button width

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#61]
These buttons are normally smaller than the current width minimum

![image](https://user-images.githubusercontent.com/4083812/218451117-4f5ef896-47bd-45a6-9e71-888f50473e8a.png)

**Comment by apoapostolov** [comment]
Thank you in advance!

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
