### ISSUE TITLE
[FEATURE] Settings to work with User Flags (setups)

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#62]
This is related to https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/9 because I am looking for a way to remove those stuck settings for strikes and reset to default. 

Please expose the user flags in a JSON format in the Settings of the Core Mod. This will be a dialog called in Settings that contains a multiline text field to expose the current user flags and be able to delete or modify them. This would allow:

- Import / Export between users as a copy/paste instead of macro command. Allows DM to share to players a preset text instead of have to run them online and use command to pass around the setups. 
- Reset User flags to default (resets all changes and setups made to the system plugin defaults)

**Comment by Larkinabout** [comment]
You can use `game.tokenActionHud.resetUserFlags()` and `game.tokenActionHud.resetActorFlags()` to reset the subcategories and actions respectively, though it does it for every actor. There's also the 'Reset HUD' module setting, though that does nothing more than the macro commands.

I do like the idea of an import/export feature.

**Comment by Larkinabout** [comment]
Import/export going t be a way off, but I added a 'Reset Actions' button in the 'Customise Categories' dialog available by clicking the book icon:
![image](https://user-images.githubusercontent.com/105953297/230748794-c439fc5f-fb7b-4c23-9f94-0aa6f0ae206e.png)

**Comment by apoapostolov** [comment]
Thank you, this helps with all customized items that are no longer there.

**Comment by Larkinabout** [comment]
With Token Action HUD Core 1.4.2, the HUD data is stored in json files within the 'data/token-action-hud-core/world/' folder. This may be easier to manage directly than any setting screen would be able to do.

If you're happy with managing them that way, I'm inclined to close this issue.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.12.
