### ISSUE TITLE
[BUG] Each element in an element is repeated 4 times

### ISSUE THREAD

**Issue by cgplayer2000** [Larkinabout/fvtt-token-action-hud-core#64]
![image](https://user-images.githubusercontent.com/10798879/219807732-16889bbb-51b5-4a9d-b552-89e7bcad763a.png)

![image](https://user-images.githubusercontent.com/10798879/219814143-3ac791ab-d48a-48e4-8e8a-bf56c74a415f.png)

I click on each of the categories.  Whatever drops down is repeated 4 times, which gets pretty massive on the Conditions category.  It happens with PCs or NPCs.  I've tested it with my normal module load, and with only Token Action HUD Core and Token Action HUD 5e installed.  The problem persists.  I thought that this might have been directly related to [https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/66](url) but the difference is that I get multiples of everything in the HUD, not just the spells.  

**Versions:**
- Token Action HUD Core: 1.2.1
- Token Action HUD System: token-action-hud-dnd5e 1.2.1
- System: 5e v2.1.4
- Foundry VTT: 10.291
- Browser: Google Chrome Version 110.0.5481.104

I attempted to clear up the token with the macro from Larkinabout/fvtt-token-action-hud-core#66 but no joy.  I uninstalled both modules and re-installed them.  No change.  But, as far as I can tell, it has only happened on actors that I had placed an item modified with Items with Spells 5e.

**Comment by Larkinabout** [comment]
This should now be fixed in Token Action HUD Core 1.2.2. I'll leave this issue open for a little while for feedback.

**Comment by Aragith** [comment]
It looks like, so far, the element replication has been addressed. However, now I cannot seem to add a ranged option for thrown weapons.

**Comment by tehguitarist** [comment]
Also seeing doubles of the old Javelin trick. Three in inventory, six show up in the HUD.
<img width="1005" alt="Screenshot 2023-02-21 at 5 18 20 pm" src="https://user-images.githubusercontent.com/28495826/220263866-038dd240-13ec-44db-82eb-973038e0475a.png">

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
