### ISSUE TITLE
[BUG] Strike Auxiliary Actions Duplicated When Added via Kits

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#65]
Auxiliary actions (Draw, Sheathe) are duplicated when items are added via kits from compendium packs.

**Comment by Larkinabout** [comment]
This should now be fixed in Token Action HUD Core 1.2.2. I'll leave this issue open for a little while for feedback.

**Comment by tehguitarist** [comment]
This seems to have fixed it, but I needed to rebuild the character for it to work. Existing duplicated stayed where they were.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
