### ISSUE TITLE
Items with Spells sprouts duplicates in spell menu

### ISSUE THREAD

**Issue by Jefferydo** [Larkinabout/fvtt-token-action-hud-core#66]
I used the **Items with Spells** module to load a staff with 18 spells. It causes multiple copies of each spell to show up in the Token Action HUD, beginning with 18 duplicates of Fire Bolt.

**Versions:**
- Token Action HUD Core: 1.2.1
- Token Action HUD System: dnd5e 1.2.0
- Items with Spells: 1.3.1
- System: dnd5e 2.1.4
- Foundry VTT: 10.291
- Browser: Google Chrome 109.0.5414.120

![staff-of-surging](https://user-images.githubusercontent.com/11779859/218233964-625a2e2f-9aa6-4e41-9fed-81ace17ce688.png)

![items-with-spells-token-action-HUD](https://user-images.githubusercontent.com/11779859/218233974-22e9c2a1-6a0b-4887-a2d6-90bcd4e61b31.png)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
