### ISSUE TITLE
[BUG] Errors for players that have an "Observer" permission for a token

### ISSUE THREAD

**Issue by Solidor777** [Larkinabout/fvtt-token-action-hud-core#7]
**Describe the bug**
When a player in my game has an "Observer" permission for a token, they always get asserts on startup, or when the token data is updated.

I was able to trace this to the _updateHud() function. Modifying it to be as below fixes the problem.

```
 async _updateHud() {
        Logger.debug('Updating hud...')
        const controlledTokens = this.tokens?.controlled.filter((token) => token.isOwner);
        const character = this._getCharacter(controlledTokens)

        const multipleTokens = controlledTokens.length > 1 && !character

        if (((!character?.actor || !character.actor.isOwner) && !multipleTokens) || !this.isHudEnabled()) {
            this.close()
            return
        }

        this.actionList = await this.actionHandler.buildActionList(character)

        this.rendering = true
        this.render(true)
        Logger.debug('Hud updated')
}
```

**Comment by Larkinabout** [comment]
Hi @Solidor777, will you post the error message, so I can have a look over it please. There is a separate function for checking ownership and validity, it's also not erroring on my test of an Observer role, so I'd like to investigate further.

**Comment by Solidor777** [comment]
I reverted my changes today and reinstalled the module so I could get the message and a video of the error for you... and it didn't happen. 

Not sure what changed. Maybe there were some stale settings? But so far everything seems to be working without error now.

**Comment by Larkinabout** [comment]
New release has just dropped. I'll close this issue assuming it's resolved itself, but let me know if it recurs and I'll open it back up.
