### ISSUE TITLE
[FEATURE] Option to hide subcategories entirely

### ISSUE THREAD

**Issue by weepingminotaur** [Larkinabout/fvtt-token-action-hud-core#72]
Even if you choose not to display the title of a subcategory, it still appears grayed out. I don't want those subcategories to display at all. Users should be able to disable subcategories from module settings.

**Comment by Larkinabout** [comment]
Hi @weepingminotaur, you will need to re-lock the HUD to hide the greyed-out subcategory titles.

The unlocked HUD is equivalent to an editing mode and the subcategory titles need to appear there to allow the subcategory to be edited.

If you wish to remove a subcategory entirely, that is done from the category dialog by unlocking the HUD and right-clicking in the relevant top line button.

**Comment by weepingminotaur** [comment]
Thanks for the quick response!
