### ISSUE TITLE
[module dev FEATURE] Nested categories (in addition to the currently nested subcategories)

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#74]
We talked about this directly a bit, but I wanted to formalize it here so it doesn't get forgotten amongst everything else that goes on for this mod. It would be nice if Categories could be nested under Categories. Right now only subcategories can be nested, but it would be nice if there were nested "Tabs" instead of only having the option of nested "lists".

The specific use case I have in mind is that in pf1 an actor can have multiple Spell books (most commonly if they multiclass into different magic classes). So if I have a "Wizard" spellbook and a "Cleric" spellbook (overlook the technical aspect that cleric's don't actually have spellbooks), right now I could have 9 levels of wizard spells, then scroll...scroll...scroll and then 9 levels of cleric spells. It would be super nice if I (I as in the mod dev) could define each of those as derived categories when I'm parsing the actor items so that each wizard/cleric area could be its own defined area without needing to have both visible.

Heck, it might even be useful for a user to be able to toggle subcategories back and forth between "tabbed" and "list" views.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.4.0.
