### ISSUE TITLE
[FEATURE] Hotkey to open HUD at cursor position?

### ISSUE THREAD

**Issue by Krigsmaskine** [Larkinabout/fvtt-token-action-hud-core#75]
**Describe your idea**
I'd like to be able to press a hotkey to open the hud at will, specifically at cursor position if possible. My players appreciate the hud being constantly accessible, but as a GM, my screen real estate is already cluttered enough. My first thought was to ask for the hud to be added to right click on a token, like a context menu, but that is already used with great zeal by every other module on or a near a token, so that doesn't necessarily sound like a good idea. 😄 

**Versions**
- Token Action HUD System: DnD5e 1.2.2.
- System: 2.15

**Comment by Larkinabout** [comment]
Opening the HUD at the cursor position is out of scope for the time being, but I've added a hotkey (H) to toggle the HUD, which should help with clutter. It'll be available in the next release.

**Comment by Larkinabout** [comment]
Added hotkey in Token Action HUD Core 1.3.2.
