### ISSUE TITLE
[FEATURE] designate action as non-action

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#76]
I'd like a way to designate a specific action as as non-action so that it can't be clicked. I don't want it to change when it's hovered. I want to be able to use this for a "button" that should be there, but is currently disabled for some reason. One example is that it's for initiative, but initiative has already been rolled--I just want to show the current value without implying that the user can do something by clicking on it again.

Or possibly can still be clicked, but maybe just a 'css' class strips away hover and click styles

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.3.0.
