### ISSUE TITLE
[FEATURE] More layout options

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#77]
Right now there's grid and 'non-grid'. It would be nice if there was some sort of hybrid mode.

![image](https://user-images.githubusercontent.com/3664822/226734188-63793a63-b34a-41d3-9c41-eb100f946ab1.png)

This example is taking up more space than necessary because of the second option that has 3 choices. The top group looks fine. But the second group just looks weird because there's not enough to make a full square/box. In this case because the top grouping is already so wide, there's plenty of room for the "craft" subcategory to be 3 wide.

Maybe I just don't like the grid layout for groups of 3. Maybe a different option is to be able to specify a minimum number of grid columns and default it to 3 (or maybe even 4).

**Comment by Larkinabout** [comment]
Added in Token Action HUD Core 1.3.2.
