### ISSUE TITLE
[BUG] Grid setting doesn't take into account extra info params

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#80]
I've got an image, text, and info1 all defined on a single action. 

![image](https://user-images.githubusercontent.com/3664822/229606214-4e4ee32e-4d6d-4600-98d0-dae5e2ae5479.png)

With the grid setting turned on, the name is entirely hidden

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
