### ISSUE TITLE
[FEATURE] Allow module devs to pre-define advancedCategoryOptions

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#82]
It would be nice if I could pre-define things like `grid` or `characterCount`, it looks like if I predefine `advancedCategoryOptions ` in my exported `CATEGORIES` they're ignore/overridden somewhere

**Comment by Larkinabout** [comment]
I haven't tested but `advancedCategoryOptions` should be kept as of Token Action HUD 1.3.0.

**Comment by dmrickey** [comment]
Yup, this appears to be working now in 1.3.
