### ISSUE TITLE
[BUG] [5eDnD]

### ISSUE THREAD

**Issue by roleoutgames** [Larkinabout/fvtt-token-action-hud-core#86]
**Players Cannot See Hud**
When using the original module I have no issues with my players seeing and using the hud. I switched to the new core/dnd5e modules and everything works find for me as the GM. However, my players cannot see or use the hud despite the hud being "enabled for this user".

![Screenshot 2023-03-29 165822](https://user-images.githubusercontent.com/115042355/228666135-5e5e442a-cb71-485c-b81c-d3d76a7852e9.png)

**Versions:**
- Token Action HUD Core: [1.2.3]
- Token Action HUD System: [1.2.2]
- System: [e.g. dnd5e 2.1.5]
- Foundry VTT: [e.g. 10.291]
- Browser: [Chrome]

**Additional context**
On Forge, no other modules except dependencies enabled.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
