### ISSUE TITLE
[Bug] Category entries being duplicated many times

### ISSUE THREAD

**Issue by ra2phoenix** [Larkinabout/fvtt-token-action-hud-core#87]
All entries aside from Strike MAB rows are being duplicated between 4-6 times for me in the current versions.  I can't really determine a pattern of how many times each item dupes but it's consistent across multiple relaunches of my world.  Strangely, one actor is totally unaffected.  Everything from Attributes on is fine, it's Actions/Inventory/Feats/Spells.

![image](https://user-images.githubusercontent.com/44955795/220509481-965d9772-251e-4a34-9896-b8a625e07baf.png)

![image](https://user-images.githubusercontent.com/44955795/220509755-bfe63836-3121-4db5-9c65-e9b15cf1e6a7.png)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.0.
