### ISSUE TITLE
[SYSTEM] Coriolis

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#88]
**Describe your idea**
Add support for the Coriolis system.

**Additional context**
If anyone would like to develop this Token Action HUD system module, please let me know. System modules can be developed in your own repos. See [Developing a System Module](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module).

**Comment by Larkinabout** [comment]
Drental/fvtt-tokenactionhud#398

**Comment by kbender84** [comment]
Hi, 
I can give it a shoot and try to develop it - I've already did some scripting for yzecoriolis, but if anyone will be willing to help and answer my queries, it would be great.

**Comment by Larkinabout** [comment]
Great! Feel free to ask questions on here or hit me up on Discord: Russell#7071

**Comment by kbender84** [comment]
Works! Thanks a lot for help!
https://github.com/kbender84/token-action-hud-coriolis

Just one remark - it would be nice to have in documentation warning about the file caching - It almost made me go nuts ;)
