### ISSUE TITLE
[BUG] Subcategory data is being cached incorrectly

### ISSUE THREAD

**Issue by dmrickey** [Larkinabout/fvtt-token-action-hud-core#93]
This is the subcategory I'm building
![image](https://user-images.githubusercontent.com/3664822/230708690-288fcdd4-8d2b-49c3-8510-a4e2ab2d7a7d.png)

But the subcategory being show isn't respecting the updated `info` being passed in
![image](https://user-images.githubusercontent.com/3664822/230708711-28064c0f-1899-46f7-9bf6-7a0aee3843ca.png)

I use this `info` for spell categories to show the quantity available left to cast in this group (9999 is just a super high value for testing). Specifically in that image, if I cast one of those Burning Hands another time, the number actually available will drop to 9994 but the hud will still be showing the cached value instead of the value being built. That number doesn't reset unless I go into the core options and reset the HUD.

Here's a much more realistic example.
![image](https://user-images.githubusercontent.com/3664822/230708974-0a7e0bcd-62fc-4d07-9119-eefc5be0349c.png)
These numbers represent how many times any spell in that `<number> Level` group can be cast. With this bug, those numbers won't drop when a spell is cast.

**Versions:**
- Token Action HUD Core: [1.3.1]

**Comment by Larkinabout** [comment]
As discussed, use `addSubcategoryInfo`. Leave this open to remind me to add update functionality to `addSubcategoryToActionList`.

**Comment by dmrickey** [comment]
Previously I found that calling `addSubcategoryToActionList` with a full parent subcategory object was breaking things (at this point I don't remember what), so I needed to call it just as the wiki explained with only `type` and `id`. 

```
        /**
         * This override lets me call with a fully defined parent subcategory without blowing up core logic
         *  @override */
        addSubcategoryToActionList(parentSubcategoryData, subcategoryData) {
            const { type, id } = parentSubcategoryData;
            super.addSubcategoryToActionList({ type, id }, subcategoryData);

            if (subcategoryData.info1 && !Utils.isEmptyObject(subcategoryData.info1)) {
                const data = {
                    id: subcategoryData.id,
                    type: subcategoryData.type,
                    info: { info1: subcategoryData.info1 },
                };
                this.addSubcategoryInfo(data);
            }
        }
```

I added the second bit to my wrapper that updates the info after adding the subcategory. (I currently only use `info1` so I'm not checking 2 or 3)

**Comment by Larkinabout** [comment]
> Previously I found that calling addSubcategoryToActionList with a full parent subcategory object was breaking things (at this point I don't remember what), so I needed to call it just as the wiki explained with only type and id.

I think it was because of `nestId` and it only adding the subcategory to the predefined subcategory instead of all matching subcategories added by the user.

It's an inadvertent "feature" and `nestId` could just be ignored by `addSubcategoryToActionList' . I just need to decide if there might be reasons to get a subcategory based on a `nestId` when adding derived subcategories. This gets trickier as more TAH system modules get created as one of them might have found a need.

**Comment by Larkinabout** [comment]
Added a parameter to allow `addSubcategoryToActionList` to update existing subcategories for Token Action HUD 1.3.2, e.g., `addSubcategoryToActionList(parentSubcategory, subcategory, true)` where `true` is whether to update. The default is `false`.

It should be used carefully as it may end up overwriting a user's desired settings, especially when using it to override `advancedCategoryOptions`. As an example, for Pathfinder 2, `addSubcategoryToActionList` is used to set `advancedCategoryOptions.showTitle` to `false` for some strikes. The user may actually want to show those titles, so its not appropriate to update  `advancedCategoryOptions.showTitle` after the first instance. You could call `addSubcategoryToActionList` multiple times to update some properties but not others.

**Comment by Larkinabout** [comment]
I've added a separate method to just update existing subcategories (now called groups) for the next release.

**Comment by dmrickey** [comment]
I like calling them "groups" better. It's a bit less confusing then categories vs subcategories

**Comment by Larkinabout** [comment]
Added `updateGroup` method in Token Action HUD Core 1.4.0.
