### ISSUE TITLE
Issues with Skills and Effects sections - no break into multiple lines

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-core#95]
Skills and Effects sections seem not to break into multiple lines in 1.3.1

Tried to give the section a 100-200 pixels width to see if it would be affected, but it was ignored. 

![image](https://user-images.githubusercontent.com/4083812/230741632-6864f9f9-afcc-4202-a7bc-62ec9d7a55c6.png)

**Comment by Larkinabout** [comment]
If you figure out how to replicate it, let me know as it's not doing it for me now.

**Comment by apoapostolov** [comment]
Sure, I will test with Culprit.

**Comment by apoapostolov** [comment]
I can't easily reproduce it, it seems to happen less than 25% even without mods off, and attempts to find with Culprit didn't help. I will close now until I can confirm it better.
